local huntLocations = {
    ARR = {
        {
            zoneName = "Middle La Noscea",
            mapId   = 134,
            positions = {
                { positionId = 1, x = "16.55", y = "7.9", A = true, B = true, S = true },
                { positionId = 2, x = "18.6", y = "9.45", A = true, B = true, S = true },
                { positionId = 3, x = "15.95", y = "10.85", A = true, B = true, S = true },
                { positionId = 4, x = "17.15", y = "11.5", A = true, B = true, S = true },
                { positionId = 5, x = "13.9", y = "11.65", A = true, B = true, S = true },
                { positionId = 6, x = "18.35", y = "13.3", A = true, B = true, S = true },
                { positionId = 7, x = "13.9", y = "13.6", A = true, B = true, S = true },
                { positionId = 8, x = "20.4", y = "13.75", A = true, B = true, S = true },
                { positionId = 9, x = "16.35", y = "14.0", A = true, B = true, S = true },
                { positionId = 10, x = "15.2", y = "15.3", A = true, B = true, S = true },
                { positionId = 11, x = "20.75", y = "15.6", A = true, B = true, S = true },
                { positionId = 12, x = "18.7", y = "16.3", A = true, B = true, S = true },
                { positionId = 13, x = "23.3", y = "17.0", A = true, B = true, S = true },
                { positionId = 14, x = "17.15", y = "17.15", A = true, B = true, S = true },
                { positionId = 15, x = "18.45", y = "18.25", A = true, B = true, S = true },
                { positionId = 16, x = "21.0", y = "18.3", A = true, B = true, S = true },
                { positionId = 17, x = "23.9", y = "19.7", A = true, B = true, S = true },
                { positionId = 18, x = "19.25", y = "20.3", A = true, B = true, S = true },
                { positionId = 19, x = "24.4", y = "20.95", A = true, B = true, S = true },
                { positionId = 20, x = "20.25", y = "21.3", A = true, B = true, S = true },
                { positionId = 21, x = "19.9", y = "22.4", A = true, B = true, S = true },
                { positionId = 22, x = "22.9", y = "22.55", A = true, B = true, S = true },
                { positionId = 23, x = "25.1", y = "23.45", A = true, B = true, S = true },
                { positionId = 24, x = "23.2", y = "24.2", A = true, B = true, S = true },
            },
        },
        {
            zoneName = "Lower La Noscea",
            mapId   = 135,
            positions = {
                { positionId = 1, x = "30.05", y = "14.3", A = true, B = true, S = true },
                { positionId = 2, x = "33.0", y = "16.05", A = true, B = true, S = true },
                { positionId = 3, x = "31.5", y = "16.45", A = true, B = true, S = true },
                { positionId = 4, x = "29.0", y = "17.0", A = true, B = true, S = true },
                { positionId = 5, x = "33.5", y = "17.5", A = true, B = true, S = true },
                { positionId = 6, x = "28.55", y = "18.2", A = true, B = true, S = true },
                { positionId = 7, x = "28.65", y = "20.5", A = true, B = true, S = true },
                { positionId = 8, x = "25.1", y = "22.4", A = true, B = true, S = true },
                { positionId = 9, x = "25.95", y = "24.85", A = true, B = true, S = true },
                { positionId = 10, x = "26.45", y = "26.3", A = true, B = true, S = true },
                { positionId = 11, x = "24.3", y = "26.55", A = true, B = true, S = true },
                { positionId = 12, x = "20.25", y = "32.0", A = true, B = true, S = true },
                { positionId = 13, x = "20.1", y = "34.3", A = true, B = true, S = true },
                { positionId = 14, x = "22.7", y = "34.5", A = true, B = true, S = true },
                { positionId = 15, x = "16.9", y = "35.35", A = true, B = true, S = true },
                { positionId = 16, x = "19.2", y = "35.4", A = true, B = true, S = true },
                { positionId = 17, x = "20.6", y = "35.6", A = true, B = true, S = true },
                { positionId = 18, x = "23.15", y = "36.0", A = true, B = true, S = true },
                { positionId = 19, x = "20.0", y = "37.5", A = true, B = true, S = true },
                { positionId = 20, x = "22.9", y = "38.2", A = true, B = true, S = true },
            },
        },
        {
            zoneName = "Eastern La Noscea",
            mapId   = 137,
            positions = {
                { positionId = 1, x = "28.95", y = "19.3", A = true, B = false, S = false },
                { positionId = 2, x = "30.4", y = "19.3", A = true, B = false, S = false },
                { positionId = 3, x = "31.05", y = "19.95", A = true, B = false, S = false },
                { positionId = 4, x = "25.55", y = "20.4", A = true, B = false, S = false },
                { positionId = 5, x = "28.62", y = "20.65", A = true, B = false, S = false },
                { positionId = 6, x = "29.7", y = "21.4", A = true, B = false, S = false },
                { positionId = 7, x = "25.4", y = "21.8", A = true, B = false, S = false },
                { positionId = 8, x = "27.55", y = "25.0", A = false, B = true, S = true },
                { positionId = 9, x = "30.1", y = "25.0", A = false, B = true, S = true },
                { positionId = 10, x = "20.3", y = "25.2", A = true, B = true, S = true },
                { positionId = 11, x = "22.25", y = "25.2", A = true, B = true, S = true },
                { positionId = 12, x = "18.3", y = "26.2", A = true, B = true, S = true },
                { positionId = 13, x = "28.1", y = "26.55", A = false, B = true, S = true },
                { positionId = 14, x = "30.7", y = "26.7", A = false, B = true, S = true },
                { positionId = 15, x = "32.1", y = "27.2", A = false, B = true, S = true },
                { positionId = 16, x = "17.9", y = "27.5", A = true, B = true, S = true },
                { positionId = 17, x = "28.35", y = "28.0", A = false, B = true, S = true },
                { positionId = 18, x = "21.45", y = "28.3", A = true, B = true, S = true },
                { positionId = 19, x = "14.75", y = "28.85", A = true, B = true, S = true },
                { positionId = 20, x = "21.3", y = "29.6", A = true, B = true, S = true },
                { positionId = 21, x = "17.4", y = "29.95", A = true, B = true, S = true },
                { positionId = 22, x = "15.0", y = "30.6", A = true, B = true, S = true },
                { positionId = 23, x = "26.6", y = "30.9", A = false, B = true, S = true },
                { positionId = 24, x = "21.3", y = "31.05", A = true, B = true, S = true },
                { positionId = 25, x = "19.55", y = "31.35", A = true, B = true, S = true },
                { positionId = 26, x = "16.5", y = "32.7", A = true, B = true, S = true },
                { positionId = 27, x = "20.5", y = "33.15", A = true, B = true, S = true },
                { positionId = 28, x = "26.7", y = "33.15", A = false, B = true, S = true },
                { positionId = 29, x = "25.9", y = "33.8", A = false, B = true, S = true },
                { positionId = 30, x = "17.0", y = "33.9", A = true, B = true, S = true },
                { positionId = 31, x = "28.9", y = "35.6", A = false, B = true, S = true },
                { positionId = 32, x = "31.75", y = "36.25", A = false, B = true, S = true },
            },
        },
        {
            zoneName = "Western La Noscea",
            mapId   = 138,
            positions = {
                { positionId = 1, x = "14.55", y = "14.25", A = true, B = true, S = false },
                { positionId = 2, x = "16.1", y = "14.5", A = true, B = true, S = false },
                { positionId = 3, x = "12.9", y = "14.55", A = true, B = true, S = false },
                { positionId = 4, x = "14.2", y = "15.85", A = true, B = true, S = false },
                { positionId = 5, x = "14.35", y = "17.05", A = true, B = true, S = false },
                { positionId = 6, x = "20.2", y = "18.4", A = true, B = true, S = false },
                { positionId = 7, x = "17.05", y = "19.4", A = true, B = true, S = false },
                { positionId = 8, x = "19.6", y = "19.55", A = true, B = true, S = true },
                { positionId = 9, x = "23.15", y = "21.75", A = true, B = true, S = true },
                { positionId = 10, x = "19.85", y = "21.95", A = true, B = true, S = false },
                { positionId = 11, x = "24.7", y = "22.7", A = true, B = true, S = true },
                { positionId = 12, x = "26.1", y = "23.55", A = true, B = true, S = true },
                { positionId = 13, x = "27.65", y = "24.0", A = true, B = true, S = true },
                { positionId = 14, x = "27.65", y = "24.0", A = true, B = true, S = true },
                { positionId = 15, x = "23.3", y = "24.65", A = true, B = true, S = true },
                { positionId = 16, x = "29.0", y = "25.2", A = true, B = true, S = true },
                { positionId = 17, x = "31.25", y = "27.4", A = true, B = true, S = true },
                { positionId = 18, x = "34.05", y = "28.1", A = true, B = true, S = true },
                { positionId = 19, x = "31.75", y = "28.7", A = true, B = true, S = true },
                { positionId = 20, x = "30.8", y = "28.8", A = true, B = true, S = true },
                { positionId = 21, x = "33.0", y = "29.8", A = true, B = true, S = true },
                { positionId = 22, x = "16.15", y = "34.4", A = true, B = true, S = true },
                { positionId = 23, x = "13.95", y = "35.15", A = true, B = true, S = true },
                { positionId = 24, x = "16.95", y = "36.05", A = true, B = true, S = true },
            },
        },
        {
            zoneName = "Upper La Noscea",
            mapId   = 139,
            positions = {
                { positionId = 1, x = "27.7", y = "19.85", A = true, B = true, S = true },
                { positionId = 2, x = "29.05", y = "21.2", A = true, B = true, S = true },
                { positionId = 3, x = "28.2", y = "21.4", A = true, B = true, S = true },
                { positionId = 4, x = "10.55", y = "21.45", A = true, B = true, S = true },
                { positionId = 5, x = "12.15", y = "21.75", A = true, B = true, S = true },
                { positionId = 6, x = "28.75", y = "22.25", A = true, B = true, S = true },
                { positionId = 7, x = "11.6", y = "22.65", A = true, B = true, S = true },
                { positionId = 8, x = "12.65", y = "23.55", A = true, B = true, S = true },
                { positionId = 9, x = "35.2", y = "23.7", A = true, B = true, S = true },
                { positionId = 10, x = "27.35", y = "23.75", A = true, B = true, S = true },
                { positionId = 11, x = "29.45", y = "23.95", A = true, B = true, S = true },
                { positionId = 12, x = "33.4", y = "24.1", A = true, B = true, S = true },
                { positionId = 13, x = "30.45", y = "25.3", A = true, B = true, S = true },
                { positionId = 14, x = "28.05", y = "25.6", A = true, B = true, S = true },
                { positionId = 15, x = "12.7", y = "25.7", A = true, B = true, S = true },
                { positionId = 16, x = "33.25", y = "25.8", A = true, B = true, S = true },
                { positionId = 17, x = "13.85", y = "25.9", A = true, B = true, S = true },
            },
        },
        {
            zoneName = "Western Thanalan",
            mapId   = 140,
            positions = {
                { positionId = 1, x = "10.35", y = "5.25", A = true, B = true, S = false },
                { positionId = 2, x = "8.45", y = "5.5", A = true, B = true, S = false },
                { positionId = 3, x = "12.15", y = "5.95", A = true, B = true, S = false },
                { positionId = 4, x = "14.95", y = "6.0", A = true, B = true, S = false },
                { positionId = 5, x = "10.2", y = "6.4", A = true, B = true, S = false },
                { positionId = 6, x = "12.0", y = "7.5", A = true, B = true, S = false },
                { positionId = 7, x = "14.05", y = "7.85", A = true, B = true, S = false },
                { positionId = 8, x = "18.3", y = "15.0", A = true, B = true, S = true },
                { positionId = 9, x = "16.95", y = "16.45", A = true, B = true, S = true },
                { positionId = 10, x = "26.85", y = "16.95", A = true, B = true, S = true },
                { positionId = 11, x = "18.3", y = "17.4", A = true, B = true, S = true },
                { positionId = 12, x = "26.2", y = "19.15", A = true, B = true, S = true },
                { positionId = 13, x = "22.85", y = "20.1", A = true, B = true, S = true },
                { positionId = 14, x = "21.95", y = "22.05", A = true, B = true, S = true },
                { positionId = 15, x = "21.25", y = "24.0", A = true, B = true, S = true },
                { positionId = 16, x = "22.3", y = "24.0", A = true, B = true, S = true },
                { positionId = 17, x = "22.75", y = "24.75", A = true, B = true, S = true },
                { positionId = 18, x = "20.65", y = "25.6", A = true, B = true, S = true },
                { positionId = 19, x = "26.1", y = "26.35", A = true, B = true, S = true },
                { positionId = 20, x = "21.3", y = "27.8", A = true, B = true, S = true },
                { positionId = 21, x = "18.9", y = "29.35", A = true, B = true, S = true },
                { positionId = 22, x = "20.3", y = "29.35", A = true, B = true, S = true },
            },
        },
        {
            zoneName = "Central Thanalan",
            mapId   = 141,
            positions = {
                { positionId = 1, x = "16.3", y = "12.4", A = true, B = true, S = true },
                { positionId = 2, x = "18.0", y = "13.5", A = true, B = true, S = true },
                { positionId = 3, x = "21.75", y = "13.65", A = true, B = true, S = true },
                { positionId = 4, x = "21.9", y = "15.55", A = true, B = true, S = true },
                { positionId = 5, x = "16.6", y = "16.4", A = true, B = true, S = true },
                { positionId = 6, x = "20.8", y = "16.4", A = true, B = true, S = true },
                { positionId = 7, x = "18.1", y = "17.5", A = true, B = true, S = true },
                { positionId = 8, x = "25.4", y = "17.95", A = true, B = true, S = true },
                { positionId = 9, x = "27.75", y = "18.0", A = true, B = true, S = true },
                { positionId = 10, x = "17.9", y = "18.9", A = true, B = true, S = true },
                { positionId = 11, x = "16.3", y = "19.55", A = true, B = true, S = true },
                { positionId = 12, x = "29.5", y = "20.9", A = true, B = true, S = true },
                { positionId = 13, x = "21.6", y = "21.1", A = true, B = true, S = true },
                { positionId = 14, x = "27.2", y = "21.5", A = true, B = true, S = true },
                { positionId = 15, x = "19.2", y = "21.7", A = true, B = true, S = true },
                { positionId = 16, x = "16.95", y = "23.3", A = true, B = true, S = true },
                { positionId = 17, x = "19.45", y = "23.7", A = true, B = true, S = true },
                { positionId = 18, x = "18.7", y = "25.25", A = true, B = true, S = true },
                { positionId = 19, x = "20.45", y = "26.1", A = true, B = true, S = true },
                { positionId = 20, x = "25.8", y = "29.85", A = true, B = true, S = true },
                { positionId = 21, x = "22.4", y = "31.4", A = true, B = true, S = true },
                { positionId = 22, x = "23.9", y = "31.9", A = true, B = true, S = true },
                { positionId = 23, x = "23.7", y = "35.0", A = true, B = true, S = true },
            },
        },
        {
            zoneName = "Eastern Thanalan",
            mapId   = 145,
            positions = {
                { positionId = 1, x = "12.8", y = "15.85", A = true, B = true, S = true },
                { positionId = 2, x = "14.5", y = "16.25", A = true, B = true, S = true },
                { positionId = 3, x = "29.6", y = "17.3", A = true, B = true, S = true },
                { positionId = 4, x = "29.6", y = "17.3", A = true, B = true, S = true },
                { positionId = 5, x = "25.8", y = "17.65", A = true, B = true, S = true },
                { positionId = 6, x = "27.35", y = "17.9", A = true, B = true, S = true },
                { positionId = 7, x = "14.65", y = "18.7", A = true, B = true, S = true },
                { positionId = 8, x = "12.7", y = "18.9", A = true, B = true, S = true },
                { positionId = 9, x = "24.3", y = "18.95", A = true, B = true, S = true },
                { positionId = 10, x = "10.4", y = "19.1", A = true, B = true, S = true },
                { positionId = 11, x = "26.7", y = "19.25", A = true, B = true, S = true },
                { positionId = 12, x = "22.8", y = "19.65", A = true, B = true, S = true },
                { positionId = 13, x = "17.4", y = "20.0", A = true, B = true, S = true },
                { positionId = 14, x = "15.65", y = "20.15", A = true, B = true, S = true },
                { positionId = 15, x = "23.95", y = "21.25", A = true, B = true, S = true },
                { positionId = 16, x = "28.1", y = "21.3", A = true, B = true, S = true },
                { positionId = 17, x = "17.5", y = "21.4", A = true, B = true, S = true },
                { positionId = 18, x = "18.95", y = "22.5", A = true, B = true, S = true },
                { positionId = 19, x = "23.45", y = "22.85", A = true, B = true, S = true },
                { positionId = 20, x = "25.0", y = "23.25", A = true, B = true, S = true },
                { positionId = 21, x = "19.85", y = "24.35", A = true, B = true, S = true },
                { positionId = 22, x = "17.4", y = "24.75", A = true, B = true, S = true },
                { positionId = 23, x = "26.7", y = "25.05", A = true, B = true, S = true },
                { positionId = 24, x = "17.85", y = "25.5", A = true, B = true, S = true },
                { positionId = 25, x = "25.4", y = "25.55", A = true, B = true, S = false },
                { positionId = 26, x = "27.9", y = "25.75", A = true, B = true, S = true },
                { positionId = 27, x = "16.6", y = "25.9", A = true, B = true, S = true },
                { positionId = 28, x = "14.55", y = "26.15", A = true, B = true, S = true },
                { positionId = 29, x = "23.4", y = "26.7", A = true, B = true, S = true },
                { positionId = 30, x = "29.3", y = "26.75", A = true, B = true, S = true },
                { positionId = 31, x = "15.4", y = "26.9", A = true, B = true, S = true },
                { positionId = 32, x = "17.45", y = "28.0", A = true, B = true, S = true },
                { positionId = 33, x = "19.55", y = "28.45", A = true, B = true, S = true },
                { positionId = 34, x = "20.35", y = "28.55", A = true, B = true, S = true },
                { positionId = 35, x = "12.9", y = "29.0", A = true, B = true, S = true },
            },
        },
        {
            zoneName = "Southern Thanalan",
            mapId   = 146,
            positions = {
                { positionId = 1, x = "23.2", y = "7.95", A = true, B = true, S = false },
                { positionId = 2, x = "24.65", y = "9.35", A = true, B = true, S = false },
                { positionId = 3, x = "18.0", y = "10.2", A = true, B = true, S = false },
                { positionId = 4, x = "21.25", y = "10.85", A = true, B = true, S = false },
                { positionId = 5, x = "18.25", y = "11.2", A = true, B = true, S = false },
                { positionId = 6, x = "24.65", y = "11.45", A = true, B = true, S = false },
                { positionId = 7, x = "17.2", y = "11.7", A = true, B = true, S = false },
                { positionId = 8, x = "23.8", y = "12.45", A = true, B = true, S = false },
                { positionId = 9, x = "17.2", y = "16.95", A = true, B = true, S = false },
                { positionId = 10, x = "19.55", y = "17.2", A = true, B = true, S = false },
                { positionId = 11, x = "31.0", y = "18.4", A = true, B = true, S = true },
                { positionId = 12, x = "19.7", y = "19.25", A = true, B = true, S = true },
                { positionId = 13, x = "32.9", y = "19.85", A = true, B = true, S = true },
                { positionId = 14, x = "15.95", y = "20.25", A = true, B = true, S = false },
                { positionId = 15, x = "21.4", y = "20.75", A = true, B = true, S = true },
                { positionId = 16, x = "28.5", y = "20.75", A = true, B = true, S = true },
                { positionId = 17, x = "18.35", y = "21.2", A = true, B = true, S = true },
                { positionId = 18, x = "24.15", y = "21.3", A = true, B = true, S = true },
                { positionId = 19, x = "18.45", y = "22.9", A = true, B = true, S = true },
                { positionId = 20, x = "21.05", y = "22.9", A = true, B = true, S = true },
                { positionId = 21, x = "16.65", y = "23.15", A = true, B = true, S = true },
                { positionId = 22, x = "16.0", y = "24.45", A = true, B = true, S = true },
                { positionId = 23, x = "19.8", y = "24.7", A = true, B = true, S = true },
                { positionId = 24, x = "24.4", y = "24.85", A = true, B = true, S = true },
                { positionId = 25, x = "17.05", y = "25.7", A = true, B = true, S = true },
                { positionId = 26, x = "21.15", y = "26.35", A = true, B = true, S = true },
                { positionId = 27, x = "20.25", y = "28.5", A = true, B = true, S = true },
                { positionId = 28, x = "21.6", y = "29.9", A = true, B = true, S = true },
                { positionId = 29, x = "23.85", y = "30.4", A = true, B = true, S = true },
                { positionId = 30, x = "18.85", y = "30.55", A = true, B = true, S = true },
                { positionId = 31, x = "21.2", y = "32.15", A = true, B = true, S = true },
                { positionId = 32, x = "16.85", y = "33.05", A = true, B = true, S = true },
                { positionId = 33, x = "23.45", y = "33.3", A = true, B = true, S = true },
                { positionId = 34, x = "21.8", y = "34.3", A = true, B = true, S = true },
                { positionId = 35, x = "28.5", y = "34.7", A = true, B = true, S = true },
                { positionId = 36, x = "13.8", y = "34.85", A = true, B = true, S = true },
                { positionId = 37, x = "16.1", y = "36.8", A = true, B = true, S = true },
                { positionId = 38, x = "24.45", y = "36.9", A = true, B = true, S = true },
                { positionId = 39, x = "19.1", y = "38.4", A = true, B = true, S = true },
                { positionId = 40, x = "22.5", y = "38.65", A = true, B = true, S = true },
                { positionId = 41, x = "14.75", y = "38.85", A = true, B = true, S = true },
                { positionId = 42, x = "25.1", y = "40.85", A = true, B = true, S = true },
            },
        },
        {
            zoneName = "Northern Thanalan",
            mapId   = 147,
            positions = {
		{ positionId = 1, x = "16.05", y = "14.65", A = true, B = true, S = true },
		{ positionId = 3, x = "16.05", y = "15.95", A = true, B = true, S = true },
		{ positionId = 2, x = "17.25", y = "15.7", A = true, B = true, S = true },
		{ positionId = 5, x = "16.85", y = "16.95", A = true, B = true, S = true },
		{ positionId = 4, x = "19.05", y = "16.75", A = true, B = true, S = true },
		{ positionId = 6, x = "18.25", y = "17.5", A = true, B = true, S = true },
		{ positionId = 7, x = "18.75", y = "18.0", A = true, B = true, S = true },
		{ positionId = 8, x = "15.4", y = "18.55", A = true, B = true, S = true },
		{ positionId = 9, x = "16.35", y = "19.4", A = true, B = true, S = true },
		{ positionId = 10, x = "23.95", y = "22.85", A = true, B = true, S = true },
		{ positionId = 11, x = "24.3", y = "23.2", A = true, B = true, S = true },
		{ positionId = 12, x = "23.65", y = "24.15", A = true, B = true, S = true },
		{ positionId = 14, x = "23.6", y = "25.25", A = true, B = true, S = true },
		{ positionId = 15, x = "23.45", y = "26.3", A = true, B = true, S = true },
		{ positionId = 16, x = "22.2", y = "27.0", A = true, B = true, S = true },
		{ positionId = 17, x = "20.6", y = "27.8", A = true, B = true, S = true },
		{ positionId = 13, x = "21.05", y = "25.0", A = true, B = true, S = true },
            },
        },
        {
            zoneName = "Central Shroud",
            mapId   = 148,
            positions = {
                { positionId = 1, x = "28.75", y = "14.45", A = true, B = true, S = true },
                { positionId = 2, x = "21.75", y = "16.35", A = true, B = true, S = true },
                { positionId = 3, x = "9.55", y = "16.9", A = true, B = true, S = true },
                { positionId = 4, x = "16.65", y = "17.8", A = true, B = true, S = true },
                { positionId = 5, x = "19.1", y = "18.3", A = true, B = true, S = true },
                { positionId = 6, x = "31.1", y = "18.6", A = true, B = true, S = true },
                { positionId = 7, x = "10.05", y = "18.9", A = true, B = true, S = true },
                { positionId = 8, x = "12.1", y = "19.4", A = true, B = true, S = true },
                { positionId = 9, x = "29.1", y = "19.45", A = true, B = true, S = true },
                { positionId = 10, x = "14.25", y = "19.5", A = true, B = true, S = true },
                { positionId = 11, x = "14.25", y = "19.5", A = true, B = true, S = true },
                { positionId = 12, x = "15.8", y = "19.65", A = true, B = true, S = true },
                { positionId = 13, x = "26.75", y = "20.6", A = true, B = true, S = true },
                { positionId = 14, x = "12.75", y = "20.75", A = true, B = true, S = true },
                { positionId = 15, x = "16.05", y = "21.15", A = true, B = true, S = true },
                { positionId = 16, x = "10.45", y = "21.7", A = true, B = true, S = true },
                { positionId = 17, x = "28.25", y = "22.05", A = true, B = true, S = true },
                { positionId = 18, x = "27.05", y = "22.6", A = true, B = true, S = true },
                { positionId = 19, x = "29.65", y = "23.35", A = true, B = true, S = true },
                { positionId = 20, x = "11.6", y = "23.55", A = true, B = true, S = true },
                { positionId = 21, x = "15.85", y = "24.0", A = true, B = true, S = true },
                { positionId = 22, x = "22.05", y = "24.5", A = true, B = true, S = true },
                { positionId = 23, x = "23.4", y = "27.5", A = true, B = true, S = true },
                { positionId = 24, x = "21.6", y = "30.05", A = true, B = true, S = true },
            },
        },
        {
            zoneName = "East Shroud",
            mapId   = 152,
            positions = {
                { positionId = 1, x = "25.05", y = "9.8", A = true, B = true, S = true },
                { positionId = 2, x = "26.5", y = "11.3", A = true, B = true, S = true },
                { positionId = 3, x = "29.5", y = "11.45", A = true, B = true, S = true },
                { positionId = 4, x = "24.45", y = "11.7", A = true, B = true, S = true },
                { positionId = 5, x = "28.1", y = "12.75", A = true, B = true, S = true },
                { positionId = 6, x = "25.9", y = "13.1", A = true, B = true, S = true },
                { positionId = 7, x = "29.9", y = "13.3", A = true, B = true, S = true },
                { positionId = 8, x = "24.3", y = "15.2", A = true, B = true, S = true },
                { positionId = 9, x = "31.9", y = "15.4", A = true, B = true, S = true },
                { positionId = 10, x = "26.7", y = "16.05", A = true, B = true, S = true },
                { positionId = 11, x = "24.0", y = "16.5", A = true, B = true, S = true },
                { positionId = 12, x = "24.8", y = "17.4", A = true, B = true, S = true },
                { positionId = 13, x = "30.3", y = "17.45", A = true, B = true, S = true },
                { positionId = 14, x = "27.0", y = "17.95", A = true, B = true, S = true },
                { positionId = 15, x = "27.8", y = "18.7", A = true, B = true, S = true },
                { positionId = 16, x = "25.7", y = "20.35", A = true, B = true, S = true },
                { positionId = 17, x = "29.0", y = "20.5", A = true, B = true, S = true },
                { positionId = 18, x = "31.7", y = "21.5", A = true, B = true, S = true },
                { positionId = 19, x = "16.85", y = "21.75", A = true, B = true, S = true },
                { positionId = 20, x = "23.0", y = "21.75", A = true, B = true, S = true },
                { positionId = 21, x = "21.25", y = "21.8", A = true, B = true, S = true },
                { positionId = 22, x = "27.6", y = "22.6", A = true, B = true, S = true },
                { positionId = 23, x = "17.4", y = "22.9", A = true, B = true, S = true },
                { positionId = 24, x = "13.6", y = "23.25", A = true, B = true, S = true },
                { positionId = 25, x = "25.3", y = "23.65", A = true, B = true, S = true },
                { positionId = 26, x = "15.6", y = "23.9", A = true, B = true, S = true },
                { positionId = 27, x = "27.7", y = "24.6", A = true, B = true, S = true },
                { positionId = 28, x = "25.8", y = "25.2", A = true, B = true, S = true },
                { positionId = 29, x = "14.35", y = "25.35", A = true, B = true, S = true },
                { positionId = 30, x = "19.05", y = "25.4", A = true, B = true, S = true },
                { positionId = 31, x = "14.5", y = "27.65", A = true, B = true, S = true },
                { positionId = 32, x = "22.0", y = "28.1", A = true, B = true, S = true },
                { positionId = 33, x = "19.95", y = "28.75", A = true, B = true, S = true },
                { positionId = 34, x = "22.1", y = "29.6", A = true, B = true, S = true },
                { positionId = 35, x = "23.8", y = "30.85", A = true, B = true, S = true },
            },
        },
        {
            zoneName = "South Shroud",
            mapId   = 153,
            positions = {
                { positionId = 1, x = "27.75", y = "17.65", A = true, B = true, S = true },
                { positionId = 2, x = "24.35", y = "18.2", A = true, B = true, S = true },
                { positionId = 3, x = "16.9", y = "18.4", A = true, B = true, S = true },
                { positionId = 4, x = "18.8", y = "18.45", A = true, B = true, S = true },
                { positionId = 5, x = "22.15", y = "19.25", A = true, B = true, S = true },
                { positionId = 6, x = "15.8", y = "19.7", A = true, B = true, S = true },
                { positionId = 7, x = "26.95", y = "19.9", A = true, B = true, S = true },
                { positionId = 8, x = "17.0", y = "21.45", A = true, B = true, S = true },
                { positionId = 9, x = "21.4", y = "21.6", A = true, B = true, S = true },
                { positionId = 10, x = "18.6", y = "22.05", A = true, B = true, S = true },
                { positionId = 11, x = "22.65", y = "22.65", A = true, B = true, S = true },
                { positionId = 12, x = "27.05", y = "22.75", A = true, B = true, S = true },
                { positionId = 13, x = "16.9", y = "23.65", A = true, B = true, S = true },
                { positionId = 14, x = "31.7", y = "23.75", A = true, B = true, S = true },
                { positionId = 15, x = "32.7", y = "23.95", A = true, B = true, S = true },
                { positionId = 16, x = "23.0", y = "24.15", A = true, B = true, S = true },
                { positionId = 17, x = "28.85", y = "24.65", A = true, B = true, S = true },
                { positionId = 18, x = "30.55", y = "25.6", A = true, B = true, S = true },
                { positionId = 19, x = "22.65", y = "25.65", A = true, B = true, S = true },
                { positionId = 20, x = "19.4", y = "27.4", A = true, B = true, S = true },
                { positionId = 21, x = "16.15", y = "27.6", A = true, B = true, S = true },
                { positionId = 22, x = "21.4", y = "27.65", A = true, B = true, S = true },
                { positionId = 23, x = "15.7", y = "28.55", A = true, B = true, S = true },
                { positionId = 24, x = "19.0", y = "28.65", A = true, B = true, S = true },
                { positionId = 25, x = "17.25", y = "30.5", A = true, B = true, S = true },
                { positionId = 26, x = "18.25", y = "30.9", A = true, B = true, S = true },
                { positionId = 27, x = "16.3", y = "32.05", A = true, B = true, S = true },
                { positionId = 28, x = "17.15", y = "32.45", A = true, B = true, S = true },
            },
        },
        {
            zoneName = "North Shroud",
            mapId   = 154,
            positions = {
                { positionId = 1, x = "23.45", y = "19.95", A = true, B = true, S = true },
                { positionId = 2, x = "24.45", y = "20.2", A = true, B = true, S = true },
                { positionId = 3, x = "18.65", y = "20.4", A = true, B = true, S = true },
                { positionId = 4, x = "22.65", y = "20.7", A = true, B = true, S = true },
                { positionId = 5, x = "28.6", y = "21.65", A = true, B = true, S = true },
                { positionId = 6, x = "27.65", y = "22.25", A = true, B = true, S = true },
                { positionId = 7, x = "25.95", y = "22.75", A = true, B = true, S = true },
                { positionId = 8, x = "22.15", y = "23.75", A = true, B = true, S = true },
                { positionId = 9, x = "27.95", y = "24.3", A = true, B = true, S = true },
                { positionId = 10, x = "16.65", y = "25.4", A = true, B = true, S = true },
                { positionId = 11, x = "24.8", y = "25.7", A = true, B = true, S = true },
                { positionId = 12, x = "25.8", y = "26.05", A = true, B = true, S = true },
                { positionId = 13, x = "18.2", y = "27.05", A = true, B = true, S = true },
                { positionId = 14, x = "27.05", y = "27.2", A = true, B = false, S = true },
                { positionId = 15, x = "22.45", y = "28.15", A = true, B = true, S = true },
                { positionId = 16, x = "15.95", y = "28.25", A = true, B = true, S = true },
                { positionId = 17, x = "24.55", y = "28.3", A = true, B = true, S = true },
                { positionId = 18, x = "19.4", y = "28.6", A = true, B = true, S = true },
                { positionId = 19, x = "18.15", y = "28.95", A = true, B = true, S = true },
                { positionId = 20, x = "21.55", y = "30.05", A = true, B = true, S = true },
            },
        },
        {
            zoneName = "Coerthas Central Highlands",
            mapId   = 155,
            positions = {
                { positionId = 1, x = "32.05", y = "7.1", A = true, B = true, S = true },
                { positionId = 2, x = "28.9", y = "7.75", A = true, B = true, S = true },
                { positionId = 3, x = "22.95", y = "8.05", A = true, B = true, S = true },
                { positionId = 4, x = "24.65", y = "9.1", A = true, B = true, S = true },
                { positionId = 5, x = "30.15", y = "10.6", A = true, B = true, S = true },
                { positionId = 6, x = "25.3", y = "11.2", A = true, B = true, S = true },
                { positionId = 7, x = "28.1", y = "11.45", A = true, B = true, S = true },
                { positionId = 8, x = "8.95", y = "11.9", A = true, B = true, S = true },
                { positionId = 9, x = "30.2", y = "12.6", A = true, B = true, S = true },
                { positionId = 10, x = "10.8", y = "12.85", A = true, B = true, S = true },
                { positionId = 11, x = "27.05", y = "13.45", A = true, B = true, S = true },
                { positionId = 12, x = "8.85", y = "13.5", A = true, B = true, S = true },
                { positionId = 13, x = "24.8", y = "13.5", A = true, B = true, S = true },
                { positionId = 14, x = "11.75", y = "14.25", A = true, B = true, S = true },
                { positionId = 15, x = "31.5", y = "14.3", A = true, B = true, S = true },
                { positionId = 16, x = "8.85", y = "14.8", A = true, B = true, S = true },
                { positionId = 17, x = "28.4", y = "14.85", A = true, B = true, S = true },
                { positionId = 18, x = "35.05", y = "15.3", A = true, B = true, S = true },
                { positionId = 19, x = "5.25", y = "16.0", A = true, B = true, S = true },
                { positionId = 20, x = "20.55", y = "16.25", A = true, B = true, S = true },
                { positionId = 21, x = "4.15", y = "16.6", A = true, B = true, S = true },
                { positionId = 22, x = "31.9", y = "16.95", A = true, B = true, S = true },
                { positionId = 23, x = "5.6", y = "18.05", A = true, B = true, S = true },
                { positionId = 24, x = "14.3", y = "18.05", A = true, B = true, S = true },
                { positionId = 25, x = "10.5", y = "18.25", A = true, B = true, S = true },
                { positionId = 26, x = "15.4", y = "18.5", A = true, B = true, S = true },
                { positionId = 27, x = "19.55", y = "18.65", A = true, B = true, S = true },
                { positionId = 28, x = "21.55", y = "18.8", A = true, B = true, S = true },
                { positionId = 29, x = "17.5", y = "18.85", A = true, B = true, S = true },
                { positionId = 30, x = "11.55", y = "19.65", A = true, B = true, S = true },
                { positionId = 31, x = "14.3", y = "19.8", A = true, B = true, S = true },
                { positionId = 32, x = "6.45", y = "19.85", A = true, B = true, S = true },
                { positionId = 33, x = "24.6", y = "20.0", A = true, B = true, S = true },
                { positionId = 34, x = "16.85", y = "20.5", A = true, B = true, S = true },
                { positionId = 35, x = "27.1", y = "20.65", A = true, B = true, S = true },
                { positionId = 36, x = "8.35", y = "21.0", A = true, B = true, S = true },
                { positionId = 37, x = "24.15", y = "21.7", A = true, B = true, S = true },
                { positionId = 38, x = "27.4", y = "22.15", A = true, B = true, S = true },
                { positionId = 39, x = "34.8", y = "22.75", A = true, B = true, S = true },
                { positionId = 40, x = "35.8", y = "23.05", A = true, B = true, S = true },
                { positionId = 41, x = "32.8", y = "23.6", A = true, B = true, S = true },
                { positionId = 42, x = "24.65", y = "23.75", A = true, B = true, S = true },
                { positionId = 43, x = "13.4", y = "25.25", A = true, B = true, S = true },
                { positionId = 44, x = "14.9", y = "25.6", A = true, B = true, S = true },
                { positionId = 45, x = "28.1", y = "25.6", A = true, B = true, S = true },
                { positionId = 46, x = "25.65", y = "25.65", A = true, B = true, S = true },
                { positionId = 47, x = "23.45", y = "26.8", A = true, B = true, S = true },
                { positionId = 48, x = "9.0", y = "27.25", A = true, B = true, S = true },
                { positionId = 49, x = "11.0", y = "27.3", A = true, B = true, S = true },
                { positionId = 50, x = "15.8", y = "27.45", A = true, B = true, S = true },
                { positionId = 51, x = "29.3", y = "27.65", A = true, B = true, S = true },
                { positionId = 52, x = "12.65", y = "28.05", A = true, B = true, S = true },
                { positionId = 53, x = "21.4", y = "28.2", A = true, B = true, S = true },
                { positionId = 54, x = "6.6", y = "28.7", A = true, B = true, S = true },
                { positionId = 55, x = "15.5", y = "28.7", A = true, B = true, S = true },
                { positionId = 56, x = "11.05", y = "28.95", A = true, B = true, S = true },
                { positionId = 57, x = "19.8", y = "29.2", A = true, B = true, S = true },
                { positionId = 58, x = "17.7", y = "29.35", A = true, B = true, S = true },
                { positionId = 59, x = "30.3", y = "29.8", A = true, B = true, S = true },
                { positionId = 60, x = "30.75", y = "31.05", A = true, B = true, S = true },
            },
        },
        {
            zoneName = "Mor Dhona",
            mapId   = 156,
            positions = {
                { positionId = 1, x = "30.6", y = "6.4", A = true, B = true, S = false },
                { positionId = 2, x = "29.1", y = "6.5", A = true, B = true, S = false },
                { positionId = 3, x = "32.3", y = "6.9", A = true, B = true, S = false },
                { positionId = 4, x = "29.1", y = "7.7", A = true, B = true, S = false },
                { positionId = 5, x = "19.15", y = "8.1", A = true, B = true, S = true },
                { positionId = 6, x = "26.8", y = "8.5", A = true, B = true, S = false },
                { positionId = 7, x = "32.45", y = "8.6", A = true, B = true, S = false },
                { positionId = 8, x = "27.15", y = "8.85", A = true, B = true, S = false },
                { positionId = 9, x = "32.3", y = "10.2", A = true, B = true, S = false },
                { positionId = 10, x = "16.05", y = "10.45", A = true, B = true, S = true },
                { positionId = 11, x = "14.0", y = "10.5", A = true, B = true, S = true },
                { positionId = 12, x = "27.4", y = "10.6", A = true, B = true, S = false },
                { positionId = 13, x = "24.85", y = "10.65", A = true, B = true, S = false },
                { positionId = 14, x = "23.2", y = "10.7", A = true, B = true, S = false },
                { positionId = 15, x = "31.45", y = "11.3", A = true, B = true, S = false },
                { positionId = 16, x = "11.9", y = "11.8", A = true, B = true, S = true },
                { positionId = 17, x = "15.75", y = "11.8", A = true, B = true, S = true },
                { positionId = 18, x = "33.6", y = "12.05", A = true, B = true, S = false },
                { positionId = 19, x = "13.65", y = "12.15", A = true, B = true, S = true },
                { positionId = 20, x = "23.4", y = "12.2", A = true, B = true, S = false },
                { positionId = 21, x = "25.2", y = "12.7", A = true, B = true, S = false },
                { positionId = 22, x = "26.8", y = "12.7", A = true, B = true, S = false },
                { positionId = 23, x = "28.25", y = "13.55", A = true, B = true, S = false },
                { positionId = 24, x = "12.7", y = "13.75", A = true, B = true, S = true },
                { positionId = 25, x = "14.2", y = "13.85", A = true, B = true, S = true },
                { positionId = 26, x = "9.8", y = "13.9", A = false, B = false, S = true },
                { positionId = 27, x = "32.4", y = "14.35", A = true, B = true, S = false },
                { positionId = 28, x = "28.95", y = "14.75", A = true, B = true, S = false },
                { positionId = 29, x = "30.15", y = "15.05", A = true, B = true, S = false },
                { positionId = 30, x = "10.6", y = "15.15", A = false, B = false, S = true },
                { positionId = 31, x = "16.4", y = "15.6", A = true, B = true, S = true },
                { positionId = 32, x = "12.6", y = "16.0", A = false, B = false, S = true },
                { positionId = 33, x = "12.25", y = "16.85", A = false, B = false, S = true },
                { positionId = 34, x = "16.8", y = "17.4", A = true, B = true, S = true },
            },
        },
        {
            zoneName = "Outer La Noscea",
            mapId   = 180,
            positions = {
                { positionId = 1, x = "27.0", y = "5.2", A = true, B = true, S = true },
                { positionId = 2, x = "21.5", y = "6.85", A = true, B = true, S = true },
                { positionId = 3, x = "22.45", y = "6.85", A = true, B = true, S = true },
                { positionId = 4, x = "27.4", y = "7.25", A = true, B = true, S = true },
                { positionId = 5, x = "24.55", y = "7.35", A = true, B = true, S = true },
                { positionId = 6, x = "21.75", y = "8.35", A = true, B = true, S = true },
                { positionId = 7, x = "23.65", y = "9.25", A = true, B = true, S = true },
                { positionId = 8, x = "21.8", y = "9.5", A = true, B = true, S = true },
                { positionId = 9, x = "21.9", y = "10.3", A = true, B = true, S = true },
                { positionId = 10, x = "15.6", y = "10.35", A = true, B = true, S = true },
                { positionId = 11, x = "15.4", y = "12.65", A = true, B = true, S = true },
                { positionId = 12, x = "23.0", y = "13.2", A = true, B = true, S = true },
                { positionId = 13, x = "14.1", y = "14.05", A = true, B = true, S = true },
                { positionId = 14, x = "21.35", y = "14.6", A = true, B = true, S = true },
                { positionId = 15, x = "15.25", y = "14.8", A = true, B = true, S = true },
                { positionId = 16, x = "19.0", y = "15.1", A = true, B = true, S = true },
                { positionId = 17, x = "22.9", y = "15.15", A = true, B = true, S = true },
                { positionId = 18, x = "24.6", y = "16.15", A = true, B = true, S = true },
                { positionId = 19, x = "13.55", y = "16.2", A = true, B = true, S = true },
                { positionId = 20, x = "23.0", y = "16.2", A = true, B = true, S = true },
                { positionId = 21, x = "14.7", y = "16.85", A = true, B = true, S = true },
                { positionId = 22, x = "16.45", y = "17.8", A = true, B = true, S = true },
                { positionId = 23, x = "15.1", y = "18.05", A = true, B = true, S = true },
            },
        },
    },
    HW = {
        {
            zoneName = "Coerthas Western Highlands",
            mapId   = 397,
            positions = {
                { positionId = 1, x = "28.0", y = "7.85", A = true, B = true, S = true },
                { positionId = 2, x = "35.6", y = "9.6", A = true, B = true, S = true },
                { positionId = 3, x = "26.1", y = "11.55", A = true, B = true, S = true },
                { positionId = 4, x = "15.1", y = "12.1", A = true, B = true, S = true },
                { positionId = 5, x = "6.65", y = "12.45", A = true, B = true, S = true },
                { positionId = 6, x = "36.25", y = "12.5", A = true, B = true, S = true },
                { positionId = 7, x = "29.35", y = "13.0", A = true, B = true, S = true },
                { positionId = 8, x = "18.0", y = "13.1", A = true, B = true, S = true },
                { positionId = 9, x = "10.0", y = "13.2", A = true, B = true, S = true },
                { positionId = 10, x = "27.5", y = "15.9", A = true, B = true, S = true },
                { positionId = 11, x = "11.55", y = "17.3", A = true, B = true, S = true },
                { positionId = 12, x = "21.95", y = "17.65", A = true, B = true, S = true },
                { positionId = 13, x = "32.5", y = "17.65", A = true, B = true, S = true },
                { positionId = 14, x = "18.05", y = "18.95", A = true, B = true, S = true },
                { positionId = 15, x = "22.1", y = "20.7", A = true, B = true, S = true },
                { positionId = 16, x = "34.05", y = "20.8", A = true, B = true, S = true },
                { positionId = 17, x = "27.95", y = "21.4", A = true, B = true, S = false },
                { positionId = 18, x = "33.8", y = "22.5", A = true, B = true, S = false },
                { positionId = 19, x = "17.3", y = "25.8", A = true, B = true, S = true },
                { positionId = 20, x = "29.95", y = "26.75", A = true, B = true, S = false },
                { positionId = 21, x = "23.5", y = "28.1", A = true, B = true, S = false },
                { positionId = 22, x = "16.7", y = "29.65", A = true, B = true, S = true },
                { positionId = 23, x = "18.7", y = "31.2", A = true, B = true, S = false },
                { positionId = 24, x = "25.0", y = "32.35", A = true, B = true, S = false },
            },
        },
        {
            zoneName = "The Dravanian Forelands",
            mapId   = 398,
            positions = {
                { positionId = 1, x = "26.4", y = "7.5", A = true, B = true, S = true },
                { positionId = 2, x = "33.9", y = "8.55", A = true, B = true, S = true },
                { positionId = 3, x = "16.9", y = "11.3", A = true, B = false, S = true },
                { positionId = 4, x = "34.85", y = "13.55", A = false, B = true, S = true },
                { positionId = 5, x = "13.6", y = "15.05", A = true, B = false, S = true },
                { positionId = 6, x = "32.5", y = "18.25", A = false, B = true, S = true },
                { positionId = 7, x = "21.4", y = "19.8", A = true, B = true, S = true },
                { positionId = 8, x = "28.9", y = "21.8", A = true, B = true, S = true },
                { positionId = 9, x = "25.7", y = "24.85", A = true, B = true, S = true },
                { positionId = 10, x = "38.6", y = "25.6", A = false, B = true, S = true },
                { positionId = 11, x = "12.35", y = "27.6", A = true, B = true, S = true },
                { positionId = 12, x = "34.6", y = "28.75", A = false, B = true, S = true },
                { positionId = 13, x = "20.05", y = "30.2", A = true, B = true, S = true },
                { positionId = 14, x = "27.75", y = "30.8", A = true, B = true, S = true },
                { positionId = 15, x = "14.3", y = "31.35", A = true, B = true, S = true },
                { positionId = 16, x = "24.9", y = "32.4", A = true, B = true, S = true },
                { positionId = 17, x = "21.15", y = "33.8", A = true, B = true, S = true },
                { positionId = 18, x = "10.25", y = "35.25", A = true, B = true, S = true },
                { positionId = 19, x = "27.4", y = "37.25", A = true, B = true, S = true },
                { positionId = 20, x = "17.95", y = "38.75", A = true, B = true, S = true },
            },
        },
        {
            zoneName = "The Dravanian Hinterlands",
            mapId   = 399,
            positions = {
                { positionId = 1, x = "13.1", y = "16.45", A = true, B = true, S = true },
                { positionId = 2, x = "26.65", y = "16.6", A = true, B = true, S = true },
                { positionId = 3, x = "26.85", y = "20.05", A = true, B = true, S = true },
                { positionId = 4, x = "31.8", y = "20.15", A = true, B = true, S = true },
                { positionId = 5, x = "9.35", y = "21.35", A = true, B = true, S = true },
                { positionId = 6, x = "15.05", y = "21.6", A = true, B = true, S = true },
                { positionId = 7, x = "35.95", y = "21.85", A = true, B = true, S = true },
                { positionId = 8, x = "5.4", y = "22.15", A = true, B = true, S = true },
                { positionId = 9, x = "24.0", y = "23.5", A = true, B = true, S = true },
                { positionId = 10, x = "33.95", y = "24.1", A = true, B = true, S = true },
                { positionId = 11, x = "15.1", y = "25.45", A = true, B = true, S = true },
                { positionId = 12, x = "26.8", y = "25.45", A = true, B = true, S = true },
                { positionId = 13, x = "34.2", y = "26.85", A = true, B = true, S = true },
                { positionId = 14, x = "8.6", y = "28.1", A = true, B = true, S = true },
                { positionId = 15, x = "38.0", y = "28.4", A = true, B = true, S = true },
                { positionId = 16, x = "12.6", y = "29.25", A = true, B = true, S = true },
                { positionId = 17, x = "26.6", y = "29.4", A = true, B = true, S = true },
                { positionId = 18, x = "15.5", y = "32.05", A = true, B = true, S = true },
                { positionId = 19, x = "8.45", y = "34.0", A = true, B = true, S = true },
                { positionId = 20, x = "14.5", y = "35.65", A = true, B = true, S = true },
                { positionId = 21, x = "26.25", y = "36.9", A = true, B = true, S = true },
                { positionId = 22, x = "16.15", y = "37.75", A = true, B = true, S = true },
            },
        },
        {
            zoneName = "The Churning Mists",
            mapId   = 400,
            positions = {
                { positionId = 1, x = "25.85", y = "7.95", A = true, B = true, S = true },
                { positionId = 2, x = "9.5", y = "8.5", A = true, B = true, S = true },
                { positionId = 3, x = "28.25", y = "10.6", A = true, B = true, S = true },
                { positionId = 4, x = "7.4", y = "11.7", A = true, B = true, S = true },
                { positionId = 5, x = "15.2", y = "14.5", A = true, B = true, S = true },
                { positionId = 6, x = "7.9", y = "15.8", A = true, B = true, S = true },
                { positionId = 7, x = "6.85", y = "20.25", A = true, B = true, S = true },
                { positionId = 8, x = "11.9", y = "20.3", A = true, B = true, S = true },
                { positionId = 9, x = "28.5", y = "20.35", A = true, B = true, S = true },
                { positionId = 10, x = "24.9", y = "20.5", A = true, B = true, S = true },
                { positionId = 11, x = "33.5", y = "20.85", A = true, B = true, S = true },
                { positionId = 12, x = "14.0", y = "23.55", A = true, B = true, S = true },
                { positionId = 13, x = "18.2", y = "24.35", A = true, B = true, S = true },
                { positionId = 14, x = "37.2", y = "26.2", A = true, B = true, S = true },
                { positionId = 15, x = "26.4", y = "27.6", A = true, B = true, S = true },
                { positionId = 16, x = "16.9", y = "28.0", A = true, B = true, S = true },
                { positionId = 17, x = "36.05", y = "29.05", A = true, B = true, S = true },
                { positionId = 18, x = "15.8", y = "30.25", A = true, B = true, S = true },
                { positionId = 19, x = "22.45", y = "31.1", A = true, B = true, S = true },
                { positionId = 20, x = "31.95", y = "32.65", A = true, B = true, S = true },
                { positionId = 21, x = "6.45", y = "35.65", A = true, B = true, S = true },
                { positionId = 22, x = "10.05", y = "38.7", A = true, B = true, S = true },
            },
        },
        {
            zoneName = "The Sea of Clouds",
            mapId   = 401,
            positions = {
                { positionId = 1, x = "29.35", y = "6.55", A = true, B = true, S = true },
                { positionId = 2, x = "15.55", y = "7.5", A = true, B = true, S = true },
                { positionId = 3, x = "21.75", y = "7.65", A = true, B = true, S = true },
                { positionId = 4, x = "7.5", y = "8.35", A = true, B = true, S = true },
                { positionId = 5, x = "36.9", y = "8.65", A = true, B = true, S = true },
                { positionId = 6, x = "19.25", y = "9.45", A = true, B = true, S = true },
                { positionId = 7, x = "23.25", y = "10.0", A = true, B = true, S = true },
                { positionId = 8, x = "25.05", y = "13.1", A = true, B = true, S = true },
                { positionId = 9, x = "15.4", y = "14.6", A = true, B = true, S = true },
                { positionId = 10, x = "37.4", y = "14.65", A = true, B = true, S = true },
                { positionId = 11, x = "21.55", y = "16.05", A = true, B = true, S = true },
                { positionId = 12, x = "9.05", y = "16.65", A = true, B = true, S = true },
                { positionId = 13, x = "31.45", y = "19.05", A = true, B = true, S = true },
                { positionId = 14, x = "6.5", y = "19.3", A = true, B = true, S = true },
                { positionId = 15, x = "36.5", y = "21.15", A = true, B = true, S = true },
                { positionId = 16, x = "20.85", y = "21.5", A = true, B = true, S = true },
                { positionId = 17, x = "14.55", y = "23.5", A = true, B = true, S = true },
                { positionId = 18, x = "24.45", y = "25.25", A = true, B = true, S = true },
                { positionId = 19, x = "26.1", y = "29.1", A = true, B = true, S = true },
                { positionId = 20, x = "13.75", y = "29.15", A = true, B = true, S = true },
                { positionId = 21, x = "17.9", y = "29.85", A = true, B = true, S = true },
                { positionId = 22, x = "34.05", y = "31.55", A = true, B = true, S = true },
                { positionId = 23, x = "18.3", y = "31.65", A = true, B = true, S = true },
                { positionId = 24, x = "26.6", y = "33.7", A = true, B = true, S = true },
                { positionId = 25, x = "31.65", y = "36.1", A = true, B = true, S = true },
                { positionId = 26, x = "36.2", y = "38.5", A = true, B = true, S = true },
            },
        },
        {
            zoneName = "Azys Lla",
            mapId   = 402,
            positions = {
                { positionId = 1, x = "32.7", y = "5.75", A = true, B = true, S = true },
                { positionId = 2, x = "37.7", y = "7.1", A = true, B = true, S = true },
                { positionId = 3, x = "17.3", y = "8.55", A = true, B = true, S = true },
                { positionId = 4, x = "27.65", y = "11.15", A = true, B = true, S = true },
                { positionId = 5, x = "33.8", y = "12.85", A = true, B = true, S = true },
                { positionId = 6, x = "18.5", y = "13.25", A = true, B = true, S = true },
                { positionId = 7, x = "27.4", y = "15.8", A = true, B = true, S = true },
                { positionId = 8, x = "13.9", y = "16.9", A = true, B = true, S = true },
                { positionId = 9, x = "9.45", y = "26.5", A = true, B = true, S = true },
                { positionId = 10, x = "34.35", y = "26.65", A = true, B = true, S = true },
                { positionId = 11, x = "38.95", y = "27.6", A = true, B = true, S = true },
                { positionId = 12, x = "29.85", y = "28.75", A = true, B = true, S = true },
                { positionId = 13, x = "16.1", y = "29.4", A = true, B = true, S = true },
                { positionId = 14, x = "11.3", y = "30.35", A = true, B = true, S = true },
                { positionId = 15, x = "35.9", y = "30.8", A = true, B = true, S = true },
                { positionId = 16, x = "8.25", y = "34.0", A = true, B = true, S = true },
                { positionId = 17, x = "36.25", y = "34.15", A = true, B = true, S = true },
                { positionId = 18, x = "29.65", y = "35.05", A = true, B = true, S = true },
                { positionId = 19, x = "36.35", y = "37.15", A = true, B = true, S = true },
                { positionId = 20, x = "12.85", y = "38.2", A = true, B = true, S = true },
            },
        },
    },
    SB = {
        {
            zoneName = "The Fringes",
            mapId   = 612,
            positions = {
                { positionId = 1, x = "18.25", y = "8.45", A = true, B = true, S = true },
                { positionId = 2, x = "21.2", y = "10.55", A = false, B = true, S = false },
                { positionId = 3, x = "25.35", y = "11.75", A = false, B = true, S = true },
                { positionId = 4, x = "14.35", y = "12.4", A = true, B = true, S = false },
                { positionId = 5, x = "17.8", y = "12.75", A = true, B = true, S = true },
                { positionId = 6, x = "10.45", y = "14.55", A = true, B = true, S = false },
                { positionId = 7, x = "34.65", y = "17.5", A = true, B = true, S = false },
                { positionId = 8, x = "12.25", y = "18.0", A = true, B = true, S = false },
                { positionId = 9, x = "24.1", y = "18.15", A = false, B = true, S = false },
                { positionId = 10, x = "33.75", y = "20.9", A = false, B = true, S = false },
                { positionId = 11, x = "17.5", y = "21.75", A = true, B = true, S = false },
                { positionId = 12, x = "27.75", y = "23.5", A = true, B = true, S = true },
                { positionId = 13, x = "16.65", y = "24.3", A = true, B = true, S = true },
                { positionId = 14, x = "8.7", y = "25.25", A = true, B = true, S = false },
                { positionId = 15, x = "15.35", y = "26.25", A = true, B = true, S = false },
                { positionId = 16, x = "25.2", y = "28.4", A = true, B = true, S = true },
                { positionId = 17, x = "8.3", y = "30.55", A = true, B = true, S = true },
                { positionId = 18, x = "28.95", y = "30.8", A = false, B = true, S = true },
                { positionId = 19, x = "25.85", y = "31.9", A = true, B = true, S = false },
                { positionId = 20, x = "33.3", y = "33.35", A = true, B = true, S = false },
            },
        },
        {
            zoneName = "The Ruby Sea",
            mapId   = 613,
            positions = {
                { positionId = 1, x = "7.5", y = "5.9", A = false, B = true, S = false },
                { positionId = 2, x = "25.95", y = "7.05", A = true, B = true, S = true },
                { positionId = 3, x = "18.85", y = "8.65", A = true, B = true, S = true },
                { positionId = 4, x = "16.55", y = "10.6", A = false, B = true, S = false },
                { positionId = 5, x = "14.45", y = "13.9", A = true, B = true, S = false },
                { positionId = 6, x = "36.5", y = "17.95", A = false, B = true, S = false },
                { positionId = 7, x = "34.95", y = "21.15", A = false, B = true, S = true },
                { positionId = 8, x = "5.05", y = "22.95", A = true, B = true, S = false },
                { positionId = 9, x = "32.05", y = "24.3", A = true, B = true, S = true },
                { positionId = 10, x = "25.3", y = "26.2", A = false, B = true, S = false },
                { positionId = 11, x = "6.9", y = "29.8", A = true, B = true, S = true },
                { positionId = 12, x = "27.25", y = "31.6", A = true, B = true, S = true },
                { positionId = 13, x = "23.95", y = "33.2", A = true, B = true, S = true },
                { positionId = 14, x = "31.05", y = "38.75", A = true, B = true, S = false },
            },
        },
        {
            zoneName = "Yanxia",
            mapId   = 614,
            positions = {
                { positionId = 1, x = "21.6", y = "9.45", A = true, B = true, S = true },
                { positionId = 2, x = "27.1", y = "10.4", A = true, B = true, S = true },
                { positionId = 3, x = "18.35", y = "10.5", A = false, B = true, S = false },
                { positionId = 4, x = "28.7", y = "11.35", A = true, B = true, S = true },
                { positionId = 5, x = "23.65", y = "11.5", A = true, B = true, S = true },
                { positionId = 6, x = "16.9", y = "13.8", A = true, B = true, S = true },
                { positionId = 7, x = "18.25", y = "16.15", A = true, B = true, S = false },
                { positionId = 8, x = "32.35", y = "18.5", A = false, B = true, S = false },
                { positionId = 9, x = "24.6", y = "21.7", A = false, B = true, S = false },
                { positionId = 10, x = "34.15", y = "26.6", A = false, B = true, S = false },
                { positionId = 11, x = "23.6", y = "27.25", A = false, B = true, S = false },
                { positionId = 12, x = "12.3", y = "30.6", A = true, B = true, S = true },
                { positionId = 13, x = "17.65", y = "34.3", A = true, B = true, S = true },
                { positionId = 14, x = "29.85", y = "35.3", A = false, B = true, S = false },
            },
        },
        {
            zoneName = "The Peaks",
            mapId   = 620,
            positions = {
                { positionId = 1, x = "26.95", y = "7.95", A = true, B = true, S = false },
                { positionId = 2, x = "11.2", y = "8.2", A = true, B = true, S = true },
                { positionId = 3, x = "32.05", y = "8.3", A = true, B = true, S = true },
                { positionId = 4, x = "26.25", y = "12.0", A = true, B = true, S = false },
                { positionId = 5, x = "8.7", y = "12.25", A = true, B = true, S = true },
                { positionId = 6, x = "36.35", y = "12.45", A = true, B = true, S = true },
                { positionId = 7, x = "5.65", y = "14.75", A = true, B = true, S = true },
                { positionId = 8, x = "23.35", y = "14.95", A = true, B = true, S = true },
                { positionId = 9, x = "25.35", y = "20.15", A = true, B = true, S = false },
                { positionId = 10, x = "16.65", y = "23.1", A = true, B = true, S = false },
                { positionId = 11, x = "23.75", y = "24.25", A = true, B = true, S = true },
                { positionId = 12, x = "7.8", y = "25.85", A = true, B = true, S = false },
                { positionId = 13, x = "18.1", y = "26.7", A = true, B = true, S = true },
                { positionId = 14, x = "12.6", y = "28.3", A = true, B = true, S = true },
                { positionId = 15, x = "26.65", y = "29.85", A = false, B = true, S = false },
                { positionId = 16, x = "11.75", y = "32.85", A = true, B = true, S = true },
                { positionId = 17, x = "5.85", y = "34.8", A = true, B = true, S = false },
                { positionId = 18, x = "23.65", y = "36.6", A = true, B = true, S = true },
            },
        },
        {
            zoneName = "The Lochs",
            mapId   = 621,
            positions = {
                { positionId = 1, x = "18.3", y = "7.5", A = false, B = true, S = false },
                { positionId = 2, x = "29.1", y = "8.0", A = true, B = false, S = true },
                { positionId = 3, x = "6.45", y = "8.25", A = true, B = true, S = true },
                { positionId = 4, x = "22.5", y = "10.35", A = false, B = true, S = false },
                { positionId = 5, x = "35.1", y = "11.1", A = true, B = true, S = false },
                { positionId = 6, x = "7.7", y = "14.1", A = true, B = true, S = false },
                { positionId = 7, x = "25.05", y = "16.5", A = false, B = true, S = false },
                { positionId = 8, x = "13.95", y = "20.55", A = true, B = true, S = true },
                { positionId = 9, x = "18.8", y = "25.6", A = true, B = true, S = true },
                { positionId = 10, x = "23.45", y = "25.85", A = false, B = true, S = false },
                { positionId = 11, x = "7.4", y = "26.3", A = true, B = false, S = true },
                { positionId = 12, x = "4.6", y = "29.3", A = true, B = true, S = false },
                { positionId = 13, x = "6.95", y = "31.1", A = true, B = true, S = false },
                { positionId = 14, x = "18.95", y = "31.75", A = true, B = true, S = false },
                { positionId = 15, x = "24.55", y = "32.95", A = true, B = true, S = true },
                { positionId = 16, x = "10.45", y = "33.7", A = false, B = true, S = true },
                { positionId = 17, x = "26.45", y = "34.55", A = true, B = true, S = false },
                { positionId = 18, x = "3.1", y = "34.95", A = true, B = false, S = true },
                { positionId = 19, x = "30.1", y = "36.35", A = true, B = false, S = true },
            },
        },
        {
            zoneName = "The Azim Steppe",
            mapId   = 622,
            positions = {
                { positionId = 1, x = "27.35", y = "9.0", A = true, B = true, S = true },
                { positionId = 2, x = "13.5", y = "10.15", A = true, B = true, S = true },
                { positionId = 3, x = "19.35", y = "10.25", A = true, B = true, S = true },
                { positionId = 4, x = "34.65", y = "15.05", A = true, B = true, S = true },
                { positionId = 5, x = "22.35", y = "15.95", A = true, B = true, S = true },
                { positionId = 6, x = "12.45", y = "17.25", A = true, B = true, S = true },
                { positionId = 7, x = "27.9", y = "18.8", A = true, B = true, S = true },
                { positionId = 8, x = "17.4", y = "18.9", A = true, B = true, S = true },
                { positionId = 9, x = "9.65", y = "22.35", A = true, B = true, S = true },
                { positionId = 10, x = "14.95", y = "25.5", A = true, B = true, S = true },
                { positionId = 11, x = "27.9", y = "25.7", A = true, B = true, S = true },
                { positionId = 12, x = "9.75", y = "25.9", A = true, B = true, S = true },
                { positionId = 13, x = "11.4", y = "28.35", A = true, B = true, S = true },
                { positionId = 14, x = "15.6", y = "30.3", A = true, B = true, S = true },
                { positionId = 15, x = "24.25", y = "30.3", A = true, B = true, S = true },
                { positionId = 16, x = "21.85", y = "34.2", A = true, B = true, S = true },
                { positionId = 17, x = "26.7", y = "34.25", A = true, B = true, S = true },
                { positionId = 18, x = "17.6", y = "34.4", A = true, B = true, S = true },
            },
        },
    },
    ShB = {
        {
            zoneName = "Lakeland",
            mapId   = 813,
            positions = {
                { positionId = 1, x = "19.7", y = "9.75", A = true, B = true, S = true },
                { positionId = 2, x = "36.65", y = "12.2", A = true, B = true, S = true },
                { positionId = 3, x = "23.25", y = "12.35", A = true, B = true, S = true },
                { positionId = 4, x = "11.7", y = "12.65", A = true, B = true, S = true },
                { positionId = 5, x = "27.65", y = "15.35", A = true, B = true, S = true },
                { positionId = 6, x = "35.1", y = "15.95", A = true, B = true, S = true },
                { positionId = 7, x = "11.3", y = "17.25", A = true, B = true, S = true },
                { positionId = 8, x = "29.5", y = "19.3", A = true, B = true, S = true },
                { positionId = 9, x = "30.75", y = "22.65", A = true, B = true, S = true },
                { positionId = 10, x = "7.8", y = "22.75", A = true, B = true, S = false },
                { positionId = 11, x = "18.3", y = "23.0", A = true, B = true, S = true },
                { positionId = 12, x = "25.5", y = "23.9", A = true, B = true, S = true },
                { positionId = 13, x = "13.7", y = "24.5", A = true, B = true, S = true },
                { positionId = 14, x = "35.7", y = "27.05", A = true, B = true, S = false },
                { positionId = 15, x = "23.1", y = "29.7", A = true, B = true, S = true },
                { positionId = 16, x = "27.9", y = "30.9", A = true, B = true, S = true },
                { positionId = 17, x = "35.2", y = "32.2", A = true, B = true, S = false },
                { positionId = 18, x = "26.65", y = "37.2", A = true, B = true, S = true },
            },
        },
        {
            zoneName = "Kholusia",
            mapId   = 814,
            positions = {
                { positionId = 1, x = "17.05", y = "6.9", A = true, B = true, S = true },
                { positionId = 2, x = "19.6", y = "10.6", A = true, B = true, S = true },
                { positionId = 3, x = "24.8", y = "11.4", A = true, B = true, S = true },
                { positionId = 4, x = "21.8", y = "14.05", A = true, B = true, S = true },
                { positionId = 5, x = "14.9", y = "15.75", A = true, B = true, S = true },
                { positionId = 6, x = "22.95", y = "17.55", A = true, B = true, S = true },
                { positionId = 7, x = "11.6", y = "18.7", A = true, B = true, S = true },
                { positionId = 8, x = "26.7", y = "19.25", A = true, B = true, S = true },
                { positionId = 9, x = "31.45", y = "19.65", A = true, B = true, S = true },
                { positionId = 10, x = "21.2", y = "22.5", A = true, B = true, S = true },
                { positionId = 11, x = "34.45", y = "24.15", A = true, B = true, S = true },
                { positionId = 12, x = "15.0", y = "24.3", A = true, B = true, S = true },
                { positionId = 13, x = "26.8", y = "24.35", A = true, B = true, S = true },
                { positionId = 14, x = "9.0", y = "25.6", A = true, B = true, S = true },
                { positionId = 15, x = "24.7", y = "29.85", A = true, B = true, S = true },
                { positionId = 16, x = "30.05", y = "30.05", A = true, B = true, S = true },
                { positionId = 17, x = "20.9", y = "31.3", A = true, B = true, S = true },
            },
        },
        {
            zoneName = "Amh Araeng",
            mapId   = 815,
            positions = {
                { positionId = 1, x = "16.7", y = "10.25", A = true, B = true, S = true },
                { positionId = 2, x = "22.6", y = "10.5", A = false, B = true, S = false },
                { positionId = 3, x = "10.25", y = "11.95", A = true, B = true, S = true },
                { positionId = 4, x = "28.6", y = "12.3", A = true, B = true, S = true },
                { positionId = 5, x = "30.95", y = "13.75", A = true, B = true, S = true },
                { positionId = 6, x = "19.35", y = "16.15", A = true, B = true, S = true },
                { positionId = 7, x = "11.55", y = "19.5", A = true, B = true, S = true },
                { positionId = 8, x = "28.8", y = "20.25", A = true, B = true, S = true },
                { positionId = 9, x = "33.55", y = "21.55", A = true, B = true, S = true },
                { positionId = 10, x = "16.3", y = "24.05", A = true, B = true, S = true },
                { positionId = 11, x = "19.2", y = "24.9", A = true, B = true, S = true },
                { positionId = 12, x = "28.5", y = "26.0", A = true, B = true, S = true },
                { positionId = 13, x = "19.75", y = "28.75", A = true, B = true, S = false },
                { positionId = 14, x = "23.2", y = "29.75", A = true, B = true, S = false },
                { positionId = 15, x = "17.15", y = "31.65", A = true, B = true, S = true },
                { positionId = 16, x = "33.0", y = "33.9", A = true, B = true, S = true },
                { positionId = 17, x = "30.4", y = "35.25", A = true, B = true, S = true },
                { positionId = 18, x = "19.9", y = "36.45", A = true, B = true, S = true },
            },
        },
        {
            zoneName = "Il Mheg",
            mapId   = 816,
            positions = {
                { positionId = 1, x = "29.25", y = "5.45", A = true, B = true, S = true },
                { positionId = 2, x = "25.5", y = "7.1", A = true, B = true, S = true },
                { positionId = 3, x = "33.8", y = "7.3", A = true, B = true, S = true },
                { positionId = 4, x = "20.2", y = "8.5", A = true, B = true, S = true },
                { positionId = 5, x = "31.6", y = "13.65", A = true, B = true, S = true },
                { positionId = 6, x = "11.2", y = "15.9", A = true, B = true, S = true },
                { positionId = 7, x = "27.2", y = "19.0", A = true, B = true, S = true },
                { positionId = 8, x = "10.8", y = "20.35", A = true, B = true, S = true },
                { positionId = 9, x = "7.45", y = "23.0", A = true, B = true, S = true },
                { positionId = 10, x = "7.85", y = "27.05", A = true, B = true, S = true },
                { positionId = 11, x = "19.1", y = "27.15", A = true, B = true, S = true },
                { positionId = 12, x = "22.8", y = "28.85", A = true, B = true, S = true },
                { positionId = 13, x = "9.65", y = "30.65", A = true, B = true, S = true },
                { positionId = 14, x = "24.55", y = "32.75", A = true, B = true, S = true },
                { positionId = 15, x = "13.6", y = "34.1", A = true, B = true, S = true },
                { positionId = 16, x = "19.7", y = "34.9", A = true, B = true, S = true },
                { positionId = 17, x = "24.7", y = "37.25", A = true, B = true, S = true },
            },
        },
        {
            zoneName = "The Rak'tika Greatwood",
            mapId   = 817,
            positions = {
                { positionId = 1, x = "22.5", y = "10.75", A = true, B = true, S = true },
                { positionId = 2, x = "21.95", y = "13.7", A = true, B = true, S = true },
                { positionId = 3, x = "26.35", y = "14.95", A = true, B = true, S = true },
                { positionId = 4, x = "9.5", y = "18.6", A = true, B = true, S = true },
                { positionId = 5, x = "14.9", y = "22.35", A = true, B = true, S = true },
                { positionId = 6, x = "33.35", y = "22.8", A = true, B = true, S = true },
                { positionId = 7, x = "9.9", y = "24.0", A = true, B = true, S = true },
                { positionId = 8, x = "16.7", y = "24.05", A = true, B = true, S = true },
                { positionId = 9, x = "26.3", y = "24.25", A = true, B = true, S = true },
                { positionId = 10, x = "29.7", y = "26.05", A = true, B = true, S = true },
                { positionId = 11, x = "15.1", y = "30.25", A = true, B = true, S = true },
                { positionId = 12, x = "25.3", y = "30.3", A = true, B = true, S = true },
                { positionId = 13, x = "8.5", y = "34.65", A = true, B = true, S = true },
                { positionId = 14, x = "17.8", y = "35.1", A = true, B = true, S = true },
                { positionId = 15, x = "12.05", y = "35.85", A = true, B = true, S = true },
            },
        },
        {
            zoneName = "The Tempest",
            mapId   = 818,
            positions = {
                { positionId = 1, x = "31.2", y = "4.05", A = true, B = true, S = true },
                { positionId = 2, x = "11.4", y = "5.25", A = true, B = true, S = false },
                { positionId = 3, x = "21.0", y = "7.7", A = true, B = true, S = true },
                { positionId = 4, x = "8.35", y = "8.35", A = true, B = true, S = false },
                { positionId = 5, x = "28.4", y = "8.45", A = true, B = true, S = true },
                { positionId = 6, x = "15.7", y = "10.3", A = true, B = true, S = true },
                { positionId = 7, x = "30.75", y = "10.95", A = true, B = true, S = true },
                { positionId = 8, x = "36.6", y = "11.55", A = true, B = true, S = true },
                { positionId = 9, x = "25.3", y = "12.95", A = true, B = true, S = true },
                { positionId = 10, x = "18.2", y = "13.35", A = true, B = true, S = true },
                { positionId = 11, x = "37.75", y = "16.7", A = true, B = true, S = true },
                { positionId = 12, x = "13.45", y = "17.4", A = true, B = true, S = true },
                { positionId = 13, x = "36.1", y = "19.95", A = true, B = true, S = true },
                { positionId = 14, x = "15.4", y = "20.4", A = true, B = true, S = true },
                { positionId = 15, x = "33.7", y = "21.6", A = true, B = true, S = true },
                { positionId = 16, x = "29.1", y = "22.85", A = true, B = true, S = true },
                { positionId = 17, x = "24.7", y = "24.7", A = true, B = true, S = true },
            },
        },
    },
    EW = {
        {
            zoneName = "Labyrinthos",
            mapId   = 956,
            positions = {
                { positionId = 1, x = "30.15", y = "8.35", A = true, B = true, S = true },
                { positionId = 2, x = "21.7", y = "8.5", A = false, B = true, S = false },
                { positionId = 3, x = "17.1", y = "9.45", A = true, B = true, S = true },
                { positionId = 4, x = "34.3", y = "13.5", A = true, B = true, S = true },
                { positionId = 5, x = "16.55", y = "16.3", A = true, B = true, S = true },
                { positionId = 6, x = "10.55", y = "19.25", A = true, B = true, S = true },
                { positionId = 7, x = "25.2", y = "25.5", A = true, B = true, S = true },
                { positionId = 8, x = "32.1", y = "26.0", A = true, B = true, S = true },
                { positionId = 9, x = "5.75", y = "33.85", A = true, B = true, S = true },
                { positionId = 10, x = "12.05", y = "35.4", A = true, B = true, S = true },
                { positionId = 11, x = "19.6", y = "38.35", A = true, B = true, S = true },
            },
        },
        {
            zoneName = "Thavnair",
            mapId   = 957,
            positions = {
                { positionId = 1, x = "18.65", y = "11.55", A = true, B = true, S = true },
                { positionId = 2, x = "14.55", y = "12.2", A = true, B = true, S = true },
                { positionId = 3, x = "6.7", y = "12.9", A = false, B = true, S = false },
                { positionId = 4, x = "29.5", y = "13.65", A = true, B = true, S = true },
                { positionId = 5, x = "18.15", y = "16.35", A = true, B = true, S = true },
                { positionId = 6, x = "32.8", y = "20.3", A = true, B = true, S = true },
                { positionId = 7, x = "26.5", y = "20.85", A = true, B = true, S = true },
                { positionId = 8, x = "18.4", y = "23.35", A = true, B = true, S = true },
                { positionId = 9, x = "27.65", y = "25.8", A = true, B = true, S = true },
                { positionId = 10, x = "20.25", y = "31.05", A = true, B = true, S = true },
            },
        },
        {
            zoneName = "Garlemald",
            mapId   = 958,
            positions = {
                { positionId = 1, x = "26.8", y = "7.9", A = false, B = true, S = false },
                { positionId = 2, x = "9.75", y = "11.6", A = true, B = true, S = true },
                { positionId = 3, x = "12.2", y = "12.75", A = true, B = true, S = true },
                { positionId = 4, x = "11.9", y = "17.35", A = true, B = true, S = true },
                { positionId = 5, x = "15.7", y = "19.65", A = true, B = true, S = true },
                { positionId = 6, x = "28.95", y = "20.75", A = true, B = true, S = true },
                { positionId = 7, x = "33.0", y = "21.85", A = true, B = true, S = true },
                { positionId = 8, x = "23.2", y = "25.55", A = true, B = true, S = true },
                { positionId = 9, x = "32.45", y = "32.35", A = true, B = true, S = true },
                { positionId = 10, x = "27.4", y = "34.05", A = true, B = true, S = true },
            },
        },
        {
            zoneName = "Mare Lamentorum",
            mapId   = 959,
            positions = {
                { positionId = 1, x = "18.45", y = "21.5", A = true, B = true, S = true },
                { positionId = 2, x = "24.3", y = "23.35", A = true, B = true, S = true },
                { positionId = 3, x = "10.3", y = "24.1", A = true, B = true, S = true },
                { positionId = 4, x = "17.15", y = "24.7", A = true, B = true, S = true },
                { positionId = 5, x = "28.3", y = "26.65", A = true, B = true, S = true },
                { positionId = 6, x = "36.4", y = "27.2", A = true, B = true, S = true },
                { positionId = 7, x = "16.55", y = "28.85", A = true, B = true, S = true },
                { positionId = 8, x = "29.8", y = "29.85", A = true, B = true, S = true },
                { positionId = 9, x = "24.25", y = "33.5", A = true, B = true, S = true },
                { positionId = 10, x = "21.1", y = "34.7", A = true, B = true, S = true },
            },
        },
        {
            zoneName = "Ultima Thule",
            mapId   = 960,
            positions = {
                { positionId = 1, x = "19.4", y = "10.0", A = true, B = true, S = true },
                { positionId = 2, x = "13.3", y = "10.5", A = true, B = true, S = true },
                { positionId = 3, x = "28.1", y = "12.6", A = true, B = true, S = true },
                { positionId = 4, x = "8.2", y = "20.6", A = true, B = true, S = true },
                { positionId = 5, x = "11.75", y = "21.7", A = true, B = true, S = true },
                { positionId = 6, x = "16.45", y = "25.85", A = true, B = true, S = true },
                { positionId = 7, x = "17.6", y = "30.35", A = true, B = true, S = true },
                { positionId = 8, x = "15.4", y = "32.5", A = false, B = true, S = false },
                { positionId = 9, x = "21.35", y = "34.0", A = true, B = true, S = true },
                { positionId = 10, x = "15.2", y = "35.95", A = true, B = true, S = true },
            },
        },
        {
            zoneName = "Elpis",
            mapId   = 961,
            positions = {
                { positionId = 1, x = "21.7", y = "6.05", A = true, B = true, S = true },
                { positionId = 2, x = "12.85", y = "9.8", A = true, B = true, S = true },
                { positionId = 3, x = "33.95", y = "10.85", A = true, B = true, S = true },
                { positionId = 4, x = "21.35", y = "13.45", A = true, B = true, S = true },
                { positionId = 5, x = "34.35", y = "14.2", A = true, B = true, S = true },
                { positionId = 6, x = "32.55", y = "18.6", A = true, B = true, S = true },
                { positionId = 7, x = "18.5", y = "24.45", A = true, B = true, S = true },
                { positionId = 8, x = "29.4", y = "27.65", A = true, B = true, S = true },
                { positionId = 9, x = "7.05", y = "29.05", A = true, B = true, S = true },
                { positionId = 10, x = "17.8", y = "30.15", A = true, B = true, S = true },
                { positionId = 11, x = "12.85", y = "32.1", A = true, B = true, S = true },
            },
        },
    },
    DT = {
        {
            zoneName = "Urqopacha",
            mapId   = 1187,
            positions = {
                { positionId = 1, x = "7.51", y = "25.58", A = true, B = true, S = true },
                { positionId = 2, x = "11.49", y = "9.11", A = true, B = true, S = true },
                { positionId = 3, x = "15.7", y = "24.24", A = true, B = true, S = true },
                { positionId = 4, x = "19.12", y = "14.21", A = true, B = true, S = true },
                { positionId = 5, x = "20.60", y = "23.60", A = false, B = true, S = false },
                { positionId = 6, x = "21.87", y = "20.85", A = true, B = true, S = true },
                { positionId = 7, x = "22.02", y = "16.8", A = false, B = true, S = false },
                { positionId = 8, x = "28.12", y = "22.91", A = true, B = true, S = true },
                { positionId = 9, x = "28.85", y = "9.45", A = true, B = true, S = true },
                { positionId = 10, x = "34.03", y = "19.1", A = false, B = true, S = false },
            },
        },
        {
            zoneName = "Kozama'uka",
            mapId   = 1188,
            positions = {
                { positionId = 1, x = "5.25", y = "28.81", A = true, B = true, S = true },
                { positionId = 2, x = "6.36", y = "12.13", A = true, B = true, S = true },
                { positionId = 3, x = "9.5", y = "7.85", A = true, B = true, S = true },
                { positionId = 4, x = "15.8", y = "23.75", A = true, B = true, S = true },
                { positionId = 5, x = "16.28", y = "17.3", A = true, B = true, S = true },
                { positionId = 6, x = "20.25", y = "28.4", A = true, B = true, S = true },
                { positionId = 7, x = "23.98", y = "36.64", A = true, B = true, S = true },
                { positionId = 8, x = "29.7", y = "15.7", A = false, B = true, S = false },
                { positionId = 9, x = "34.48", y = "36.39", A = false, B = true, S = false },
                { positionId = 10, x = "36.82", y = "20.4", A = true, B = true, S = true },
            },
        },
        {
            zoneName = "Yak T'el",
            mapId   = 1189,
            positions = {
                { positionId = 1, x = "6.38", y = "26.37", A = false, B = true, S = false },
                { positionId = 2, x = "8.6", y = "19.5", A = true, B = true, S = true },
                { positionId = 3, x = "13.52", y = "25.67", A = false, B = true, S = false },
                { positionId = 4, x = "13.7", y = "5.4", A = false, B = true, S = false },
                { positionId = 5, x = "21.31", y = "36.38", A = true, B = true, S = true },
                { positionId = 6, x = "21.71", y = "28.39", A = true, B = true, S = true },
                { positionId = 7, x = "23.36", y = "14.21", A = true, B = true, S = true },
                { positionId = 8, x = "24.63", y = "33.02", A = true, B = true, S = true },
                { positionId = 9, x = "26.22", y = "9.48", A = true, B = true, S = true },
                { positionId = 10, x = "33.12", y = "16.18", A = true, B = true, S = true },
            },
        },
        {
            zoneName = "Shaaloani",
            mapId   = 1190,
            positions = {
                { positionId = 1, x = "8.99", y = "16.5", A = true, B = true, S = true },
                { positionId = 2, x = "13.31", y = "27.45", A = false, B = true, S = false },
                { positionId = 3, x = "16.05", y = "8.29", A = true, B = true, S = true },
                { positionId = 4, x = "21.7", y = "33.34", A = true, B = true, S = true },
                { positionId = 5, x = "22.05", y = "28.19", A = true, B = true, S = true },
                { positionId = 6, x = "23.04", y = "18.84", A = true, B = true, S = true },
                { positionId = 7, x = "25.14", y = "23.29", A = true, B = true, S = true },
                { positionId = 8, x = "31.39", y = "23.16", A = true, B = true, S = true },
                { positionId = 9, x = "34.31", y = "6.49", A = true, B = true, S = true },
                { positionId = 10, x = "36.1", y = "19.1", A = false, B = true, S = false },
            },
        },
        {
            zoneName = "Heritage Found",
            mapId   = 1191,
            positions = {
                { positionId = 1, x = "8.17", y = "33.35", A = true, B = true, S = true },
                { positionId = 2, x = "12.67", y = "20.78", A = false, B = true, S = false },
                { positionId = 3, x = "13.7", y = "37.8", A = false, B = true, S = false },
                { positionId = 4, x = "14.47", y = "26.01", A = true, B = true, S = true },
                { positionId = 5, x = "24.05", y = "19.6", A = true, B = true, S = true },
                { positionId = 6, x = "27.13", y = "13.74", A = true, B = true, S = true },
                { positionId = 7, x = "27.4", y = "33.62", A = true, B = true, S = true },
                { positionId = 8, x = "29.57", y = "19.52", A = true, B = true, S = true },
                { positionId = 9, x = "29.53", y = "29.77", A = true, B = true, S = true },
                { positionId = 10, x = "36.65", y = "13.01", A = false, B = true, S = false },
            },
        },
        {
            zoneName = "Living Memory",
            mapId   = 1192,
            positions = {
                { positionId = 1, x = "4.15", y = "28.84", A = true, B = true, S = true },
                { positionId = 2, x = "4.3", y = "33.1", A = false, B = true, S = false },
                { positionId = 3, x = "5.05", y = "12.73", A = true, B = true, S = true },
                { positionId = 4, x = "12.36", y = "37.68", A = true, B = true, S = true },
                { positionId = 5, x = "12.82", y = "27.72", A = true, B = true, S = true },
                { positionId = 6, x = "18.83", y = "20.16", A = true, B = true, S = true },
                { positionId = 7, x = "26.86", y = "31.28", A = true, B = true, S = true },
                { positionId = 8, x = "32.88", y = "20.96", A = false, B = true, S = false },
                { positionId = 9, x = "37.11", y = "18.74", A = false, B = true, S = false },
                { positionId = 10, x = "38.87", y = "30.0", A = false, B = true, S = false },
            },
        },
    },
}

return huntLocations