FISH_TO_DESYNTH = {
    "Galadion Goby",
    "Galadion Chovy",
    "Leopard Eel",
    "Jasperhead",
    "Tarnished Shark",
    "Rosy Bream",
    "Cyan Octopus",
    "Heavenswimmer",
    "Spectral Megalodon",
    "Drunkfish",
    "Merman's Mane",
    "Heavenskey",
    "Ghost Shark",
    "Fishmonger",
    "Navigator's Print",
    "Casket Oyster",
    "Quicksilver Blade",
    "Funnel Shark",
    "Nimble Dancer",
    "Sothis",
    "Ghoul Barracuda",
    "La Noscean Jelly",
    "Sunfly",
    "Marine Bomb",
    "Shaggy Seadragon",
    "Momora Mora",
    "Merlthor Butterfly",
    "Gladius",
    "Spectral Discus",
    "Little Leviathan",
    "Sea Nettle",
    "Great Grandmarlin",
    "Shipwreck's Sail",
    "Charlatan Survivor",
    "Hi-aetherlouse",
    "Azeyma's Sleeve",
    "Aetheric Seadragon",
    "Mythril Sovereign",
    "Roguesaurus",
    "Coral Manta",
    "Floefish",
    "Megasquid",
    "Oschon's Stone",
    "Tossed Dagger",
    "Tripod Fish",
    "Net Crawler",
    "Merlthor Lobster",
    "Elder Dinichthys",
    "Spectral Sea Bo",
    "Shooting Star",
    "Hammerclaw",
    "Coccosteus",
    "Bartholomew the Chopper",
    "Prowler",
    "Mopbeard",
    "Wild Urchin",
    "Gugrusaurus",
    "Coral Seadragon",
    "The Fallen One",
    "Elasmosaurus",
    "Rhotano Wahoo",
    "Rhotano Sardine",
    "Deep Plaice",
    "Crimson Monkfish",
    "Chrome Hammerhead",
    "Ogre Eel",
    "Dark Nautilus",
    "Lampfish",
    "Spectral Bass",
    "Sabaton",
    "Aronnax",
    "Sweeper",
    "Silencer",
    "Deep-sea Eel",
    "Executioner",
    "Floating Saucer",
    "True Barramundi",
    "Prodigal Son",
    "Slipsnail",
    "Stonescale",
    "Tortoiseshell Crab",
    "Lady's Cameo",
    "Metallic Boxfish",
    "Goobbue Ray",
    "Watermoura",
    "King Cobrafish",
    "Mamahi-mahi",
    "Lavandin Remora",
    "Spectral Butterfly",
    "Cieldalaes Geode",
    "Titanshell Crab",
    "Mythril Boxfish",
    "Mistbeard's Cup",
    "Anomalocaris Saron",
    "Flaming Eel",
    "Jetborne Manta",
    "Devil's Sting",
    "Callichthyid",
    "Meandering Mora",
    "Hafgufa",
    "Thaliak Crab",
    "Star of the Destroyer",
    "True Scad",
    "Blooded Wrasse",
    "Bloodpolish Crab",
    "Blue Stitcher",
    "Bloodfresh Tuna",
    "Sunken Mask",
    "Spectral Eel",
    "Bareface",
    "Oracular Crab",
    "Dravanian Bream",
    "Skaldminni",
    "Serrated Clam",
    "Beatific Vision",
    "Exterminator",
    "Gory Tuna",
    "Ticinepomis",
    "Quartz Hammerhead",
    "Seafaring Toad",
    "Crow Puffer",
    "Rothlyt Kelp",
    "Living Lantern",
    "Honeycomb Fish",
    "Godsbed",
    "Lansquenet",
    "Thavnairian Shark",
    "Nephrite Eel",
    "Spectresaur",
    "Ginkgo Fin",
    "Garum Jug",
    "Smooth Jaguar",
    "Rothlyt Mussel",
    "Levi Elver",
    "Pearl Bombfish",
    "Trollfish",
    "Panoptes",
    "Crepe Sole",
    "Knifejaw",
    "Placodus",
    "Deepshade Sardine",
    "Sirensong Mussel",
    "Arrowhead",
    "Pink Shrimp",
    "Sirensong Mullet",
    "Selkie Puffer",
    "Poet's Pipe",
    "Marine Matanga",
    "Spectral Coelacanth",
    "Dusk Shark",
    "Mermaid Scale",
    "Broadhead",
    "Vivid Pink Shrimp",
    "Sunken Coelacanth",
    "Siren's Sigh",
    "Black-jawed Helicoprion",
    "Impostopus",
    "Jade Mantis Shrimp",
    "Nymeia's Wheel",
    "Taniwha",
    "Ruby Herring",
    "Whirlpool Turban",
    "Leopard Prawn",
    "Spear Squid",
    "Floating Lantern",
    "Rubescent Tatsunoko",
    "Hatatate",
    "Silent Shark",
    "Spectral Wrasse",
    "Mizuhiki",
    "Snapping Koban",
    "Silkweft Prawn",
    "Stingfin Trevally",
    "Swordtip Squid",
    "Mailfish",
    "Idaten's Bolt",
    "Maelstrom Turban",
    "Shoshitsuki",
    "Spadefish",
    "Glass Dragon",
    "Crimson Kelp",
    "Reef Squid",
    "Pinebark Flounder",
    "Mantle Moray",
    "Barded Lobster",
    "Shisui Goby",
    "Sanbaso",
    "Violet Sentry",
    "Spectral Snake Eel",
    "Heavensent Shark",
    "Fleeting Squid",
    "Bowbarb Lobster",
    "Pitch Pickle",
    "Senbei Octopus",
    "Tentacle Thresher",
    "Bekko Rockhugger",
    "Yellow Iris",
    "Crimson Sentry",
    "Flying Squid",
    "Hells' Claw",
    "Catching Carp",
    "Garlean Bluegill",
    "Yanxian Softshell",
    "Princess Salmon",
    "Calligraph",
    "Singular Shrimp",
    "Brocade Carp",
    "Yanxian Sturgeon",
    "Spectral Kotsu Zetsu",
    "Fishy Shark",
    "Gensui Shrimp",
    "Yato-no-kami",
    "Heron's Eel",
    "Crowshadow Mussel",
    "Yanxian Goby",
    "Iridescent Trout",
    "Un-Namazu",
    "Gakugyo",
    "Ginrin Goshiki",
    "Jewel of Plum Spring",
}

ITEM_LIST = require("vac_lists").Item_List

DEBUG = true

local functions = require("functions")

local function DesynthFish()
    for _, fish in ipairs(FISH_TO_DESYNTH) do
        local fishId = functions.FindItemID(fish)
        if fishId ~= nil then
            local fishAmount = Inventory.GetItemCount(fishId)
            if fishAmount > 0 then
                functions.Echo("Desynthing: "..fish)
                for i = 1, fishAmount do
                    yield("/desynth "..fishId)
                    functions.WaitForReady()
                    functions.Wait(1)
                end
            end
        else
            functions.Echo("Fish not found: "..fish)
            return
        end
    end
end

functions.Echo("Script started: Fish Desynth")
DesynthFish()
functions.Echo("Script finished: Fish Desynth")