local huntMarks = {
    ARR = {
        B = {
            { name = "Skogs Fru", zone = "Middle La Noscea" },
            { name = "Barbastelle", zone = "Lower La Noscea" },
            { name = "Dark Helmet", zone = "Western La Noscea" },
            { name = "Bloody Mary", zone = "Eastern La Noscea" },
            { name = "Myradrosh", zone = "Upper La Noscea" },
            { name = "Vuokho", zone = "Outer La Noscea" },
            { name = "Ovjang", zone = "Central Thanalan" },
            { name = "Sewer Syrup", zone = "Western Thanalan" },
            { name = "Gatling", zone = "Eastern Thanalan" },
            { name = "Albin the Ashen", zone = "Southern Thanalan" },
            { name = "Flame Sergeant Dalvag", zone = "Northern Thanalan" },
            { name = "White Joker", zone = "Central Shroud" },
            { name = "Monarch Ogrefly", zone = "South Shroud" },
            { name = "Stinging Sophie", zone = "East Shroud" },
            { name = "Phecda", zone = "North Shroud" },
            { name = "Naul", zone = "Coerthas Central Highlands" },
            { name = "Leech King", zone = "Mor Dhona" },
        },
        A = {
            { name = "Vogaal Ja", zone = "Middle La Noscea" },
            { name = "Unktehi", zone = "Lower La Noscea" },
            { name = "Nahn", zone = "Western La Noscea" },
            { name = "Hellsclaw", zone = "Eastern La Noscea" },
            { name = "Marberry", zone = "Upper La Noscea" },
            { name = "Cornu", zone = "Outer La Noscea" },
            { name = "Sabotender Bailarina", zone = "Central Thanalan" },
            { name = "Alectryon", zone = "Western Thanalan" },
            { name = "Maahes", zone = "Eastern Thanalan" },
            { name = "Zanig'oh", zone = "Southern Thanalan" },
            { name = "Dalvag's Final Flame", zone = "Northern Thanalan" },
            { name = "Forneus", zone = "Central Shroud" },
            { name = "Ghede Ti Malice", zone = "South Shroud" },
            { name = "Melt", zone = "East Shroud" },
            { name = "Girtab", zone = "North Shroud" },
            { name = "Marraco", zone = "Coerthas Central Highlands" },
            { name = "Kurrea", zone = "Mor Dhona" },
        },
        S = {
            { name = "Croque-Mitaine", zone = "Middle La Noscea" },
            { name = "Croakadile", zone = "Lower La Noscea" },
            { name = "Bonnacon", zone = "Western La Noscea" },
            { name = "The Garlok", zone = "Eastern La Noscea" },
            { name = "Nandi", zone = "Upper La Noscea" },
            { name = "Chernobog", zone = "Outer La Noscea" },
            { name = "Brontes", zone = "Central Thanalan" },
            { name = "Zona Seeker", zone = "Western Thanalan" },
            { name = "Lampalagua", zone = "Eastern Thanalan" },
            { name = "Nunyunuwi", zone = "Southern Thanalan" },
            { name = "Minhocao", zone = "Northern Thanalan" },
            { name = "Laideronnette", zone = "Central Shroud" },
            { name = "Mindflayer", zone = "South Shroud" },
            { name = "Wulgaru", zone = "East Shroud" },
            { name = "Thousand-cast Theda", zone = "North Shroud" },
            { name = "Safat", zone = "Coerthas Central Highlands" },
            { name = "Agrippa The Mighty", zone = "Mor Dhona" },
        },
    },
    HW = {
        B = {
            { name = "Alteci", zone = "Coerthas Western Highlands" },
            { name = "Kreutzet", zone = "Coerthas Western Highlands" },
            { name = "Gnath Cometdrone", zone = "The Dravanian Forelands" },
            { name = "Thextera", zone = "The Dravanian Forelands" },
            { name = "Scitalis", zone = "The Churning Mists" },
            { name = "The Scarecrow", zone = "The Churning Mists" },
            { name = "Squonk", zone = "The Sea of Clouds" },
            { name = "Sanu Vali of Dancing Wings", zone = "The Sea of Clouds" },
            { name = "Pterygotus", zone = "The Dravanian Hinterlands" },
            { name = "False Gigantopithecus", zone = "The Dravanian Hinterlands" },
            { name = "Lycidas", zone = "Azys Lla" },
            { name = "Omni", zone = "Azys Lla" },
        },
        A = {
            { name = "Mirka", zone = "Coerthas Western Highlands" },
            { name = "Lyuba", zone = "Coerthas Western Highlands" },
            { name = "Pylraster", zone = "The Dravanian Forelands" },
            { name = "Lord of the Wyverns", zone = "The Dravanian Forelands" },
            { name = "Bune", zone = "The Churning Mists" },
            { name = "Agathos", zone = "The Churning Mists" },
            { name = "Enkelados", zone = "The Sea of Clouds" },
            { name = "Sisiutl", zone = "The Sea of Clouds" },
            { name = "Slipkinx Steeljoints", zone = "The Dravanian Hinterlands" },
            { name = "Stolas", zone = "The Dravanian Hinterlands" },
            { name = "Campacti", zone = "Azys Lla" },
            { name = "Stench Blossom", zone = "Azys Lla" },
        },
        S = {
            { name = "Kaiser Behemoth", zone = "Coerthas Western Highlands" },
            { name = "Senmurv", zone = "The Dravanian Forelands" },
            { name = "Gandarewa", zone = "The Churning Mists" },
            { name = "Bird of Paradise", zone = "The Sea of Clouds" },
            { name = "The Pale Rider", zone = "The Dravanian Hinterlands" },
            { name = "Leucrotta", zone = "Azys Lla" },
        },
    },
    SB = {
        B = {
            { name = "Shadow-dweller Yamini", zone = "The Fringes" },
            { name = "Ouzelum", zone = "The Fringes" },
            { name = "Deidar", zone = "Yanxia" },
            { name = "Gyorai Quickstrike", zone = "Yanxia" },
            { name = "Guhuo Niao", zone = "The Ruby Sea" },
            { name = "Gauki Strongblade", zone = "The Ruby Sea" },
            { name = "Gwas-y-neidr", zone = "The Peaks" },
            { name = "Buccaboo", zone = "The Peaks" },
            { name = "Aswang", zone = "The Azim Steppe" },
            { name = "Kurma", zone = "The Azim Steppe" },
            { name = "Kiwa", zone = "The Lochs" },
            { name = "Manes", zone = "The Lochs" },
        },
        A = {
            { name = "Orcus", zone = "The Fringes" },
            { name = "Erle", zone = "The Fringes" },
            { name = "Gajasura", zone = "Yanxia" },
            { name = "Angada", zone = "Yanxia" },
            { name = "Funa Yurei", zone = "The Ruby Sea" },
            { name = "Oni Yumemi", zone = "The Ruby Sea" },
            { name = "Vochstein", zone = "The Peaks" },
            { name = "Aqrabuamelu", zone = "The Peaks" },
            { name = "Girimekhala", zone = "The Azim Steppe" },
            { name = "Sum", zone = "The Azim Steppe" },
            { name = "Mahisha", zone = "The Lochs" },
            { name = "Luminare", zone = "The Lochs" },
        },
        S = {
            { name = "Udumbara", zone = "The Fringes" },
            { name = "Gamma", zone = "Yanxia" },
            { name = "Okina", zone = "The Ruby Sea" },
            { name = "Bone Crawler", zone = "The Peaks" },
            { name = "Orghana", zone = "The Azim Steppe" },
            { name = "Salt and Light", zone = "The Lochs" },
        },
    },
    ShB = {
        B = {
            { name = "La Velue", zone = "Lakeland" },
            { name = "Itzpapalotl", zone = "Lakeland" },
            { name = "Domovoi", zone = "Il Mheg" },
            { name = "Vulpangue", zone = "Il Mheg" },
            { name = "Coquecigrue", zone = "Kholusia" },
            { name = "Indomitable", zone = "Kholusia" },
            { name = "Worm of the Well", zone = "Amh Araeng" },
            { name = "Juggler Hecatomb", zone = "Amh Araeng" },
            { name = "Mindmaker", zone = "The Rak'tika Greatwood" },
            { name = "Pachamama", zone = "The Rak'tika Greatwood" },
            { name = "Deacon", zone = "The Tempest" },
            { name = "Gilshs Aath Swiftclaw", zone = "The Tempest" },
        },
        A = {
            { name = "Nariphon", zone = "Lakeland" },
            { name = "Nuckelavee", zone = "Lakeland" },
            { name = "O Poorest Pauldia", zone = "Il Mheg" },
            { name = "The Mudman", zone = "Il Mheg" },
            { name = "Li'l Murderer", zone = "Kholusia" },
            { name = "Huracan", zone = "Kholusia" },
            { name = "Maliktender", zone = "Amh Araeng" },
            { name = "Sugaar", zone = "Amh Araeng" },
            { name = "Grassman", zone = "The Rak'tika Greatwood" },
            { name = "Supay", zone = "The Rak'tika Greatwood" },
            { name = "Baal", zone = "The Tempest" },
            { name = "Rusalka", zone = "The Tempest" },
        },
        S = {
            { name = "Tyger", zone = "Lakeland" },
            { name = "Aglaope", zone = "Il Mheg" },
            { name = "Forgiven Pedantry", zone = "Kholusia" },
            { name = "Tarchia", zone = "Amh Araeng" },
            { name = "Ixtab", zone = "The Rak'tika Greatwood" },
            { name = "Gunitt", zone = "The Tempest" },
            { name = "Forgiven Rebellion", zone = "" },
        },
    },
    EW = {
        B = {
            { name = "Ü-u-ü-u", zone = "Labyrinthos" },
            { name = "Green Archon", zone = "Labyrinthos" },
            { name = "Iravati", zone = "Thavnair" },
            { name = "Vajrakumara", zone = "Thavnair" },
            { name = "Emperor's Rose", zone = "Garlemald" },
            { name = "Warmonger", zone = "Garlemald" },
            { name = "Genesis Rock", zone = "Mare Lamentorum" },
            { name = "Daphnia Magna", zone = "Mare Lamentorum" },
            { name = "Shockmaw", zone = "Elpis" },
            { name = "Yumcax", zone = "Elpis" },
            { name = "Oskh Rhei", zone = "Ultima Thule" },
            { name = "Level Cheater", zone = "Ultima Thule" },
        },
        A = {
            { name = "Hulder", zone = "Labyrinthos" },
            { name = "Storsie", zone = "Labyrinthos" },
            { name = "Sugriva", zone = "Thavnair" },
            { name = "Yilan", zone = "Thavnair" },
            { name = "Aegeiros", zone = "Garlemald" },
            { name = "Minerva", zone = "Garlemald" },
            { name = "Mousse Princess", zone = "Mare Lamentorum" },
            { name = "Lunatender Queen", zone = "Mare Lamentorum" },
            { name = "Petalodus", zone = "Elpis" },
            { name = "Gurangatch", zone = "Elpis" },
            { name = "Arch-Eta", zone = "Ultima Thule" },
            { name = "Fan Ail", zone = "Ultima Thule" },
        },
        S = {
            { name = "Burfurlur the Canny", zone = "Labyrinthos" },
            { name = "Sphatika", zone = "Thavnair" },
            { name = "Armstrong", zone = "Garlemald" },
            { name = "Ruminator", zone = "Mare Lamentorum" },
            { name = "Ophioneus", zone = "Elpis" },
            { name = "Narrow-rift", zone = "Ultima Thule" },
            { name = "Ker", zone = "" },
        },
    },
    DT = {
        B = {
            { name = "Go'ozoabek'be", zone = "Kozama'uka" },
            { name = "The Slammer", zone = "Kozama'uka" },
            { name = "Chupacabra", zone = "Urqopacha" },
            { name = "Mad Maguey", zone = "Urqopacha" },
            { name = "Leafscourge Hadoll Ja", zone = "Yak T'el" },
            { name = "Xty'iinbek", zone = "Yak T'el" },
            { name = "Nopalitender Fabuloso", zone = "Shaaloani" },
            { name = "Uktena", zone = "Shaaloani" },
            { name = "Gallowsbeak", zone = "Heritage Found" },
            { name = "Gargant", zone = "Heritage Found" },
            { name = "13th Child", zone = "Living Memory" },
            { name = "Jewel Bearer", zone = "Living Memory" },
        },
        A = {
            { name = "Pkuucha", zone = "Kozama'uka" },
            { name = "The Raintriller", zone = "Kozama'uka" },
            { name = "Nechuciho", zone = "Urqopacha" },
            { name = "Queen Hawk", zone = "Urqopacha" },
            { name = "Rrax Yity'a", zone = "Yak T'el" },
            { name = "Starcrier", zone = "Yak T'el" },
            { name = "Keheniheyamewi", zone = "Shaaloani" },
            { name = "Yehehetoaua'pyo", zone = "Shaaloani" },
            { name = "Heshuala", zone = "Heritage Found" },
            { name = "Urna Variabilis", zone = "Heritage Found" },
            { name = "Cat's Eye", zone = "Living Memory" },
            { name = "Sally the Sweeper", zone = "Living Memory" },
        },
        S = {
            { name = "Ihnuxokiy", zone = "Kozama'uka" },
            { name = "Kirlirger the Abhorrent", zone = "Urqopacha" },
            { name = "Neyoozoteel", zone = "Yak T'el" },
            { name = "Sansheya", zone = "Shaaloani" },
            { name = "Atticus the Primogenitor", zone = "Heritage Found" },
            { name = "The Forecaster", zone = "Living Memory" },
            { name = "Arch Aethereater", zone = "" },
        },
    },
}

return huntMarks